#!/usr/bin/env python3
"""Fetch the stb header collection from the badc vendor-deps mirror.

After this runs, ``demos/stb/<header>.h`` exists for each header
in ``WANTED`` and is ready for badc to compile against.

Pulls from the `kromych/badc` GitHub release rather than upstream
to avoid CI flakes against the upstream host. stb does not cut
versioned releases -- the asset is pinned to a specific commit
on `nothings/stb@master`; the filename embeds the commit author
date as a synthetic version + the commit SHA short-prefix.
`_fetch` verifies a pinned sha256 before extraction. See
``scripts/vendor_deps/README.md`` for the auth model.

Idempotent: safe to call from CI before each smoke run. Output is
suppressed unless something fails -- pass ``-v`` to see every step.
"""

from __future__ import annotations

import argparse
import shutil
import sys
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "scripts" / "vendor_deps"))
import _fetch  # noqa: E402

VERSION = "20260415"
UPSTREAM_SHA = "31c1ad37456438565541f4919958214b6e762fb4"  # github nothings/stb @ master
ASSET = f"stb-{VERSION}-{UPSTREAM_SHA[:8]}.zip"
RELEASE_TAG = "vendor-deps-v1"
SHA256 = "617266695cf191a45bec2405427207011a09b057133134594b0db6ccbf9ee0b2"

# Every stb_*.h header (plus stb_vorbis.c) the upstream archive
# ships at top level. The smoke compiles a #include-everything TU
# so each new compiler change gets cross-pressure from 21
# independent header-only libraries; per-header scenarios drive
# real APIs where the surface is testable without a display
# server / audio device. Headers that can't compile yet are
# gated off inline in smoke_main.c with their own
# `/* TODO(stb-<name>): blocked on ... */` comment so the gap
# stays visible.
WANTED = (
    "stb_c_lexer.h",
    "stb_connected_components.h",
    "stb_divide.h",
    "stb_ds.h",
    "stb_dxt.h",
    "stb_easy_font.h",
    "stb_herringbone_wang_tile.h",
    "stb_hexwave.h",
    "stb_image.h",
    "stb_image_resize2.h",
    "stb_image_write.h",
    "stb_include.h",
    "stb_leakcheck.h",
    "stb_perlin.h",
    "stb_rect_pack.h",
    "stb_sprintf.h",
    "stb_textedit.h",
    "stb_tilemap_editor.h",
    "stb_truetype.h",
    "stb_vorbis.c",
    "stb_voxel_render.h",
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    def log(msg: str) -> None:
        if args.verbose:
            print(msg, file=sys.stderr)

    stb_dir = Path(__file__).resolve().parent
    cache_dir = stb_dir / ".cache"
    zip_path = cache_dir / ASSET

    cache_dir.mkdir(parents=True, exist_ok=True)
    _fetch.fetch_and_verify(RELEASE_TAG, ASSET, zip_path, SHA256, log)

    log("extracting stb")
    # The github archive zip lays everything under
    # `stb-<full-sha>/`. Hard-code the prefix; if upstream
    # changes the layout, bump it here alongside the SHA.
    prefix = f"stb-{UPSTREAM_SHA}"
    with zipfile.ZipFile(zip_path) as zf:
        for name in WANTED:
            with zf.open(f"{prefix}/{name}") as src, (stb_dir / name).open("wb") as dst:
                shutil.copyfileobj(src, dst)

    if args.verbose:
        for name in WANTED:
            p = stb_dir / name
            log(f"done -- {p} {p.stat().st_size}")

    # Generate alarm_ogg.h from the repo-root alarm.ogg payload.
    # The smoke driver embeds this byte array and feeds it to
    # stb_vorbis_open_memory as a positive decode test. Keeping
    # the .ogg as the source of truth lets us swap the test
    # asset without touching the driver.
    alarm_src = REPO_ROOT / "alarm.ogg"
    alarm_hdr = stb_dir / "alarm_ogg.h"
    if alarm_src.exists():
        data = alarm_src.read_bytes()
        rows = []
        for i in range(0, len(data), 16):
            chunk = data[i : i + 16]
            rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        body = "\n".join(rows)
        alarm_hdr.write_text(
            "/* alarm.ogg embedded as a byte array for the\n"
            " * stb_vorbis smoke scenario. Generated by\n"
            " * demos/stb/setup.py from the repo-root\n"
            " * alarm.ogg payload (mono / 48 kHz Ogg Vorbis). */\n"
            "#ifndef ALARM_OGG_H\n#define ALARM_OGG_H\n\n"
            f"static const unsigned char alarm_ogg[] = {{\n{body}\n}};\n\n"
            f"static const int alarm_ogg_len = {len(data)};\n\n"
            "#endif\n"
        )
        log(f"done -- {alarm_hdr} {len(data)}-byte payload")
    else:
        log(f"skip alarm_ogg.h -- {alarm_src} missing")
    return 0


if __name__ == "__main__":
    sys.exit(main())
