
inline_asm_rw_aggregate_param.x64:	file format elf64-x86-64

Disassembly of section .text:

<.text>:
               	xorl	%ebp, %ebp
               	movq	%rsp, %rdi
               	movl	$<entry_off>, %esi
               	callq	<addr>
               	ud2

<main>:
               	pushq	%rbp
               	movq	%rsp, %rbp
               	subq	$0x30, %rsp
               	leaq	-0x10(%rbp), %rax
               	addq	$0x0, %rax
               	xorq	%rcx, %rcx
               	movb	%cl, (%rax)
               	leaq	-0x20(%rbp), %rax
               	addq	$0x0, %rax
               	movl	$0xa, %ecx
               	movb	%cl, (%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x1, %ecx
               	movb	%cl, 0x1(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0x1(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x2, %ecx
               	movb	%cl, 0x2(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0x2(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x3, %ecx
               	movb	%cl, 0x3(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0x3(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x4, %ecx
               	movb	%cl, 0x4(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0x4(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x5, %ecx
               	movb	%cl, 0x5(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0x5(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x6, %ecx
               	movb	%cl, 0x6(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0x6(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x7, %ecx
               	movb	%cl, 0x7(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0x7(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x8, %ecx
               	movb	%cl, 0x8(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0x8(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x9, %ecx
               	movb	%cl, 0x9(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0x9(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0xa(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0xa(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0xb, %ecx
               	movb	%cl, 0xb(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0xb(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0xc, %ecx
               	movb	%cl, 0xc(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0xc(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0xd, %ecx
               	movb	%cl, 0xd(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0xd(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0xe, %ecx
               	movb	%cl, 0xe(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0xe(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0xf, %ecx
               	movb	%cl, 0xf(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0xf(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	(%rax), %rcx
               	leaq	-0x10(%rbp), %rax
               	addq	$0x0, %rax
               	movzbq	(%rax), %rax
               	leaq	-0x20(%rbp), %rdx
               	addq	$0x0, %rdx
               	movzbq	(%rdx), %rdx
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, (%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0x1(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0x1(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0x1(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0x2(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0x2(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0x2(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0x3(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0x3(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0x3(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0x4(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0x4(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0x4(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0x5(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0x5(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0x5(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0x6(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0x6(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0x6(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0x7(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0x7(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0x7(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0x8(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0x8(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0x8(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0x9(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0x9(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0x9(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0xa(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0xa(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0xa(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0xb(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0xb(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0xb(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0xc(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0xc(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0xc(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0xd(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0xd(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0xd(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0xe(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0xe(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0xe(%rcx)
               	leaq	-0x30(%rbp), %rcx
               	leaq	-0x10(%rbp), %rax
               	movzbq	0xf(%rax), %rdx
               	leaq	-0x20(%rbp), %rax
               	movzbq	0xf(%rax), %rax
               	addq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, 0xf(%rcx)
               	xorq	%rax, %rax
               	jmp	<addr>
               	leaq	-0x30(%rbp), %rdx
               	addq	%rcx, %rdx
               	movzbq	(%rdx), %rsi
               	leaq	0xa(%rcx), %rdx
               	movslq	%edx, %rdx
               	andq	$0xff, %rdx
               	cmpq	%rdx, %rsi
               	jne	<addr>
               	leaq	0x1(%rcx), %rax
               	movslq	%eax, %rcx
               	cmpq	$0x10, %rcx
               	jl	<addr>
               	movl	$0x2a, %eax
               	addq	$0x30, %rsp
               	popq	%rbp
               	retq
               	movl	$0x1, %eax
               	addq	$0x30, %rsp
               	popq	%rbp
               	retq
