
inline_asm_a64_vector_w.x64:	file format elf64-x86-64

Disassembly of section .text:

<.text>:
               	xorl	%ebp, %ebp
               	movq	%rsp, %rdi
               	movl	$<entry_off>, %esi
               	callq	<addr>
               	ud2

<main>:
               	pushq	%rbp
               	movq	%rsp, %rbp
               	subq	$0x30, %rsp
               	leaq	-0x10(%rbp), %rax
               	addq	$0x0, %rax
               	movl	$0x3, %ecx
               	movb	%cl, (%rax)
               	leaq	-0x20(%rbp), %rax
               	addq	$0x0, %rax
               	movl	$0xf0, %ecx
               	movb	%cl, (%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x14, %ecx
               	movb	%cl, 0x1(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xef, %ecx
               	movb	%cl, 0x1(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x25, %ecx
               	movb	%cl, 0x2(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xee, %ecx
               	movb	%cl, 0x2(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x36, %ecx
               	movb	%cl, 0x3(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xed, %ecx
               	movb	%cl, 0x3(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x47, %ecx
               	movb	%cl, 0x4(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xec, %ecx
               	movb	%cl, 0x4(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x58, %ecx
               	movb	%cl, 0x5(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xeb, %ecx
               	movb	%cl, 0x5(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x69, %ecx
               	movb	%cl, 0x6(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xea, %ecx
               	movb	%cl, 0x6(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x7a, %ecx
               	movb	%cl, 0x7(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xe9, %ecx
               	movb	%cl, 0x7(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x8b, %ecx
               	movb	%cl, 0x8(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xe8, %ecx
               	movb	%cl, 0x8(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x9c, %ecx
               	movb	%cl, 0x9(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xe7, %ecx
               	movb	%cl, 0x9(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0xad, %ecx
               	movb	%cl, 0xa(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xe6, %ecx
               	movb	%cl, 0xa(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0xbe, %ecx
               	movb	%cl, 0xb(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xe5, %ecx
               	movb	%cl, 0xb(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0xcf, %ecx
               	movb	%cl, 0xc(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xe4, %ecx
               	movb	%cl, 0xc(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0xe0, %ecx
               	movb	%cl, 0xd(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xe3, %ecx
               	movb	%cl, 0xd(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0xf1, %ecx
               	movb	%cl, 0xe(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xe2, %ecx
               	movb	%cl, 0xe(%rax)
               	leaq	-0x10(%rbp), %rax
               	movl	$0x2, %ecx
               	movb	%cl, 0xf(%rax)
               	leaq	-0x20(%rbp), %rax
               	movl	$0xe1, %ecx
               	movb	%cl, 0xf(%rax)
               	leaq	-0x30(%rbp), %rax
               	addq	$0x0, %rax
               	leaq	-0x10(%rbp), %rcx
               	addq	$0x0, %rcx
               	movzbq	(%rcx), %rcx
               	leaq	-0x20(%rbp), %rdx
               	addq	$0x0, %rdx
               	movzbq	(%rdx), %rdx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, (%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0x1(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0x1(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0x1(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0x2(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0x2(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0x2(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0x3(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0x3(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0x3(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0x4(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0x4(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0x4(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0x5(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0x5(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0x5(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0x6(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0x6(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0x6(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0x7(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0x7(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0x7(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0x8(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0x8(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0x8(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0x9(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0x9(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0x9(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0xa(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0xa(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0xa(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0xb(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0xb(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0xb(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0xc(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0xc(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0xc(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0xd(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0xd(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0xd(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0xe(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0xe(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0xe(%rax)
               	leaq	-0x30(%rbp), %rax
               	leaq	-0x10(%rbp), %rcx
               	movzbq	0xf(%rcx), %rdx
               	leaq	-0x20(%rbp), %rcx
               	movzbq	0xf(%rcx), %rcx
               	xorq	%rdx, %rcx
               	andq	$0xff, %rcx
               	movb	%cl, 0xf(%rax)
               	xorq	%rax, %rax
               	jmp	<addr>
               	leaq	-0x30(%rbp), %rdx
               	addq	%rcx, %rdx
               	movzbq	(%rdx), %rdx
               	leaq	-0x10(%rbp), %rsi
               	addq	%rcx, %rsi
               	movzbq	(%rsi), %rsi
               	leaq	-0x20(%rbp), %rdi
               	addq	%rcx, %rdi
               	movzbq	(%rdi), %rdi
               	xorq	%rdi, %rsi
               	andq	$0xff, %rsi
               	cmpq	%rsi, %rdx
               	jne	<addr>
               	leaq	0x1(%rcx), %rax
               	movslq	%eax, %rcx
               	cmpq	$0x10, %rcx
               	jl	<addr>
               	movl	$0x2a, %eax
               	addq	$0x30, %rsp
               	popq	%rbp
               	retq
               	movl	$0x1, %eax
               	addq	$0x30, %rsp
               	popq	%rbp
               	retq
               	jmp	<addr>
