
param_reg_swap.x64:	file format elf64-x86-64

Disassembly of section .text:

<.text>:
               	xorl	%ebp, %ebp
               	movq	%rsp, %rdi
               	movl	$<entry_off>, %esi
               	callq	<addr>
               	ud2
               	int3
               	int3
               	int3
               	int3
               	int3
               	int3
               	int3
               	int3
               	int3
               	int3
               	int3
               	int3
               	int3
               	int3
               	int3

<core>:
               	pushq	%rbp
               	movq	%rsp, %rbp
               	subq	$0x50, %rsp
               	movq	%rbx, (%rsp)
               	movq	%rdi, %r9
               	leaq	-0x40(%rbp), %rax
               	leaq	(%rax), %r8
               	leaq	(%rcx), %rax
               	movzbq	0x3(%rax), %rdi
               	movl	%edi, %edi
               	shlq	$0x8, %rdi
               	movl	%edi, %edi
               	movzbq	0x2(%rax), %rbx
               	orq	%rbx, %rdi
               	movl	%edi, %edi
               	shlq	$0x8, %rdi
               	movl	%edi, %edi
               	movzbq	0x1(%rax), %rbx
               	orq	%rbx, %rdi
               	movl	%edi, %edi
               	shlq	$0x8, %rdi
               	movl	%edi, %edi
               	movzbq	(%rax), %rax
               	orq	%rdi, %rax
               	movl	%eax, %eax
               	movl	%eax, (%r8)
               	leaq	-0x40(%rbp), %rdi
               	leaq	(%rdx), %rax
               	movzbq	0x3(%rax), %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x2(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x1(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	(%rax), %rax
               	orq	%r8, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x4(%rdi)
               	leaq	-0x40(%rbp), %rdi
               	leaq	(%rsi), %rax
               	movzbq	0x3(%rax), %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x2(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x1(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	(%rax), %rax
               	orq	%r8, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x18(%rdi)
               	leaq	-0x40(%rbp), %rdi
               	leaq	0x10(%rdx), %rax
               	addq	$0x0, %rax
               	movzbq	0x3(%rax), %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x2(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x1(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	(%rax), %rax
               	orq	%r8, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x2c(%rdi)
               	leaq	-0x40(%rbp), %rdi
               	leaq	0x4(%rcx), %rax
               	movzbq	0x3(%rax), %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x2(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x1(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	(%rax), %rax
               	orq	%r8, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x14(%rdi)
               	leaq	-0x40(%rbp), %rdi
               	leaq	0x4(%rdx), %rax
               	movzbq	0x3(%rax), %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x2(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x1(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	(%rax), %rax
               	orq	%r8, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x8(%rdi)
               	leaq	-0x40(%rbp), %rdi
               	leaq	0x4(%rsi), %rax
               	movzbq	0x3(%rax), %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x2(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x1(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	(%rax), %rax
               	orq	%r8, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x1c(%rdi)
               	leaq	-0x40(%rbp), %rdi
               	leaq	0x10(%rdx), %rax
               	addq	$0x4, %rax
               	movzbq	0x3(%rax), %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x2(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x1(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	(%rax), %rax
               	orq	%r8, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x30(%rdi)
               	leaq	-0x40(%rbp), %rdi
               	leaq	0x8(%rcx), %rax
               	movzbq	0x3(%rax), %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x2(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x1(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	(%rax), %rax
               	orq	%r8, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x28(%rdi)
               	leaq	-0x40(%rbp), %rdi
               	leaq	0x8(%rdx), %rax
               	movzbq	0x3(%rax), %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x2(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x1(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	(%rax), %rax
               	orq	%r8, %rax
               	movl	%eax, %eax
               	movl	%eax, 0xc(%rdi)
               	leaq	-0x40(%rbp), %rdi
               	leaq	0x8(%rsi), %rax
               	movzbq	0x3(%rax), %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x2(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x1(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	(%rax), %rax
               	orq	%r8, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x20(%rdi)
               	leaq	-0x40(%rbp), %rdi
               	leaq	0x10(%rdx), %rax
               	addq	$0x8, %rax
               	movzbq	0x3(%rax), %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x2(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	0x1(%rax), %rbx
               	orq	%rbx, %r8
               	movl	%r8d, %r8d
               	shlq	$0x8, %r8
               	movl	%r8d, %r8d
               	movzbq	(%rax), %rax
               	orq	%r8, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x34(%rdi)
               	leaq	-0x40(%rbp), %rdi
               	leaq	0xc(%rcx), %rax
               	movzbq	0x3(%rax), %rcx
               	movl	%ecx, %ecx
               	shlq	$0x8, %rcx
               	movl	%ecx, %ecx
               	movzbq	0x2(%rax), %r8
               	orq	%r8, %rcx
               	movl	%ecx, %ecx
               	shlq	$0x8, %rcx
               	movl	%ecx, %ecx
               	movzbq	0x1(%rax), %r8
               	orq	%r8, %rcx
               	movl	%ecx, %ecx
               	shlq	$0x8, %rcx
               	movl	%ecx, %ecx
               	movzbq	(%rax), %rax
               	orq	%rcx, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x3c(%rdi)
               	leaq	-0x40(%rbp), %rcx
               	leaq	0xc(%rdx), %rax
               	movzbq	0x3(%rax), %rdi
               	movl	%edi, %edi
               	shlq	$0x8, %rdi
               	movl	%edi, %edi
               	movzbq	0x2(%rax), %r8
               	orq	%r8, %rdi
               	movl	%edi, %edi
               	shlq	$0x8, %rdi
               	movl	%edi, %edi
               	movzbq	0x1(%rax), %r8
               	orq	%r8, %rdi
               	movl	%edi, %edi
               	shlq	$0x8, %rdi
               	movl	%edi, %edi
               	movzbq	(%rax), %rax
               	orq	%rdi, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x10(%rcx)
               	leaq	-0x40(%rbp), %rcx
               	leaq	0xc(%rsi), %rax
               	movzbq	0x3(%rax), %rsi
               	movl	%esi, %esi
               	shlq	$0x8, %rsi
               	movl	%esi, %esi
               	movzbq	0x2(%rax), %rdi
               	orq	%rdi, %rsi
               	movl	%esi, %esi
               	shlq	$0x8, %rsi
               	movl	%esi, %esi
               	movzbq	0x1(%rax), %rdi
               	orq	%rdi, %rsi
               	movl	%esi, %esi
               	shlq	$0x8, %rsi
               	movl	%esi, %esi
               	movzbq	(%rax), %rax
               	orq	%rsi, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x24(%rcx)
               	leaq	-0x40(%rbp), %rcx
               	leaq	0x10(%rdx), %rax
               	addq	$0xc, %rax
               	movzbq	0x3(%rax), %rdx
               	movl	%edx, %edx
               	shlq	$0x8, %rdx
               	movl	%edx, %edx
               	movzbq	0x2(%rax), %rsi
               	orq	%rsi, %rdx
               	movl	%edx, %edx
               	shlq	$0x8, %rdx
               	movl	%edx, %edx
               	movzbq	0x1(%rax), %rsi
               	orq	%rsi, %rdx
               	movl	%edx, %edx
               	shlq	$0x8, %rdx
               	movl	%edx, %edx
               	movzbq	(%rax), %rax
               	orq	%rdx, %rax
               	movl	%eax, %eax
               	movl	%eax, 0x38(%rcx)
               	xorq	%rcx, %rcx
               	leaq	-0x40(%rbp), %rax
               	movl	(%rax), %edx
               	leaq	-0x40(%rbp), %rax
               	movl	0x14(%rax), %eax
               	xorq	%rax, %rdx
               	leaq	-0x40(%rbp), %rax
               	movl	0x28(%rax), %eax
               	xorq	%rax, %rdx
               	leaq	-0x40(%rbp), %rax
               	movl	0x3c(%rax), %eax
               	xorq	%rdx, %rax
               	andq	$0xff, %rax
               	movb	%al, (%r9)
               	movq	(%rsp), %rbx
               	movq	%rcx, %rax
               	addq	$0x50, %rsp
               	popq	%rbp
               	retq

<main>:
               	pushq	%rbp
               	movq	%rsp, %rbp
               	subq	$0x40, %rsp
               	leaq	-0x18(%rbp), %rax
               	addq	$0x0, %rax
               	xorq	%rcx, %rcx
               	movb	%cl, (%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0x1, %ecx
               	movb	%cl, 0x1(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0x2, %ecx
               	movb	%cl, 0x2(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0x3, %ecx
               	movb	%cl, 0x3(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0x4, %ecx
               	movb	%cl, 0x4(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0x5, %ecx
               	movb	%cl, 0x5(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0x6, %ecx
               	movb	%cl, 0x6(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0x7, %ecx
               	movb	%cl, 0x7(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0x8, %ecx
               	movb	%cl, 0x8(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0x9, %ecx
               	movb	%cl, 0x9(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0xa, %ecx
               	movb	%cl, 0xa(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0xb, %ecx
               	movb	%cl, 0xb(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0xc, %ecx
               	movb	%cl, 0xc(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0xd, %ecx
               	movb	%cl, 0xd(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0xe, %ecx
               	movb	%cl, 0xe(%rax)
               	leaq	-0x18(%rbp), %rax
               	movl	$0xf, %ecx
               	movb	%cl, 0xf(%rax)
               	xorq	%rax, %rax
               	jmp	<addr>
               	leaq	-0x38(%rbp), %rdx
               	addq	%rcx, %rdx
               	movq	%rcx, %rsi
               	andq	$0xff, %rsi
               	movb	%sil, (%rdx)
               	leaq	0x1(%rcx), %rax
               	movslq	%eax, %rcx
               	cmpq	$0x20, %rcx
               	jl	<addr>
               	leaq	-0x8(%rbp), %rdi
               	leaq	-0x18(%rbp), %rsi
               	leaq	-0x38(%rbp), %rdx
               	leaq	<rip>, %rcx
               	callq	<addr>
               	leaq	-0x8(%rbp), %rax
               	movzbq	(%rax), %rax
               	addq	$0x40, %rsp
               	popq	%rbp
               	retq
