/* Linux X11/GLX dynamic-link bindings for the RGFW desktop backend
 * (demo-local). Force-included into rcore.c so badc emits the dynamic
 * imports against the system shared objects. The runtime libraries ship
 * with any X11 desktop; no -dev package is needed -- the declarations
 * come from the demo-local X11 headers. */
#ifndef RGFW_X11_LINK_H
#define RGFW_X11_LINK_H

#pragma dylib(libx11, "libX11.so.6")
#pragma binding(libx11::XAllocClassHint, "XAllocClassHint")
#pragma binding(libx11::XAllocSizeHints, "XAllocSizeHints")
#pragma binding(libx11::XChangeProperty, "XChangeProperty")
#pragma binding(libx11::XCloseDisplay, "XCloseDisplay")
#pragma binding(libx11::XConnectionNumber, "XConnectionNumber")
#pragma binding(libx11::XConvertSelection, "XConvertSelection")
#pragma binding(libx11::XCreateColormap, "XCreateColormap")
#pragma binding(libx11::XCreateFontCursor, "XCreateFontCursor")
#pragma binding(libx11::XCreateRegion, "XCreateRegion")
#pragma binding(libx11::XCreateWindow, "XCreateWindow")
#pragma binding(libx11::XDefaultRootWindow, "XDefaultRootWindow")
#pragma binding(libx11::XDefaultScreen, "XDefaultScreen")
#pragma binding(libx11::XDefaultScreenOfDisplay, "XDefaultScreenOfDisplay")
#pragma binding(libx11::XDefineCursor, "XDefineCursor")
#pragma binding(libx11::XDeleteProperty, "XDeleteProperty")
#pragma binding(libx11::XDestroyRegion, "XDestroyRegion")
#pragma binding(libx11::XDestroyWindow, "XDestroyWindow")
#pragma binding(libx11::XDisplayHeight, "XDisplayHeight")
#pragma binding(libx11::XDisplayHeightMM, "XDisplayHeightMM")
#pragma binding(libx11::XDisplayWidth, "XDisplayWidth")
#pragma binding(libx11::XDisplayWidthMM, "XDisplayWidthMM")
#pragma binding(libx11::XEventsQueued, "XEventsQueued")
#pragma binding(libx11::XFlush, "XFlush")
#pragma binding(libx11::XFree, "XFree")
#pragma binding(libx11::XFreeColors, "XFreeColors")
#pragma binding(libx11::XFreeCursor, "XFreeCursor")
#pragma binding(libx11::XFreeEventData, "XFreeEventData")
#pragma binding(libx11::XGetEventData, "XGetEventData")
#pragma binding(libx11::XGetKeyboardControl, "XGetKeyboardControl")
#pragma binding(libx11::XGetWMNormalHints, "XGetWMNormalHints")
#pragma binding(libx11::XGetWindowAttributes, "XGetWindowAttributes")
#pragma binding(libx11::XGetWindowProperty, "XGetWindowProperty")
#pragma binding(libx11::XGrabPointer, "XGrabPointer")
#pragma binding(libx11::XIconifyWindow, "XIconifyWindow")
#pragma binding(libx11::XInitThreads, "XInitThreads")
#pragma binding(libx11::XInternAtom, "XInternAtom")
#pragma binding(libx11::XKeysymToString, "XKeysymToString")
#pragma binding(libx11::XMapWindow, "XMapWindow")
#pragma binding(libx11::XMoveWindow, "XMoveWindow")
#pragma binding(libx11::XNextEvent, "XNextEvent")
#pragma binding(libx11::XOpenDisplay, "XOpenDisplay")
#pragma binding(libx11::XPeekEvent, "XPeekEvent")
#pragma binding(libx11::XPending, "XPending")
#pragma binding(libx11::XQueryPointer, "XQueryPointer")
#pragma binding(libx11::XResizeWindow, "XResizeWindow")
#pragma binding(libx11::XRootWindow, "XRootWindow")
#pragma binding(libx11::XScreenCount, "XScreenCount")
#pragma binding(libx11::XSelectInput, "XSelectInput")
#pragma binding(libx11::XSendEvent, "XSendEvent")
#pragma binding(libx11::XSetClassHint, "XSetClassHint")
#pragma binding(libx11::XSetSelectionOwner, "XSetSelectionOwner")
#pragma binding(libx11::XSetWMNormalHints, "XSetWMNormalHints")
#pragma binding(libx11::XSetWMProtocols, "XSetWMProtocols")
#pragma binding(libx11::XSetWMSizeHints, "XSetWMSizeHints")
#pragma binding(libx11::XStoreName, "XStoreName")
#pragma binding(libx11::XSync, "XSync")
#pragma binding(libx11::XTranslateCoordinates, "XTranslateCoordinates")
#pragma binding(libx11::XUngrabPointer, "XUngrabPointer")
#pragma binding(libx11::XUnmapWindow, "XUnmapWindow")
#pragma binding(libx11::XWarpPointer, "XWarpPointer")
#pragma binding(libx11::XkbKeycodeToKeysym, "XkbKeycodeToKeysym")

#pragma dylib(libgl, "libGL.so.1")
#pragma binding(libgl::glXChooseFBConfig, "glXChooseFBConfig")
#pragma binding(libgl::glXDestroyContext, "glXDestroyContext")
#pragma binding(libgl::glXGetFBConfigAttrib, "glXGetFBConfigAttrib")
#pragma binding(libgl::glXGetProcAddress, "glXGetProcAddress")
#pragma binding(libgl::glXGetProcAddressARB, "glXGetProcAddressARB")
#pragma binding(libgl::glXGetVisualFromFBConfig, "glXGetVisualFromFBConfig")
#pragma binding(libgl::glXMakeCurrent, "glXMakeCurrent")
#pragma binding(libgl::glXSwapBuffers, "glXSwapBuffers")

#pragma dylib(libxrandr, "libXrandr.so.2")
#pragma binding(libxrandr::XRRFreeCrtcInfo, "XRRFreeCrtcInfo")
#pragma binding(libxrandr::XRRFreeOutputInfo, "XRRFreeOutputInfo")
#pragma binding(libxrandr::XRRFreeScreenResources, "XRRFreeScreenResources")
#pragma binding(libxrandr::XRRGetCrtcInfo, "XRRGetCrtcInfo")
#pragma binding(libxrandr::XRRGetOutputInfo, "XRRGetOutputInfo")
#pragma binding(libxrandr::XRRGetScreenResources, "XRRGetScreenResources")
#pragma binding(libxrandr::XRRGetScreenResourcesCurrent, "XRRGetScreenResourcesCurrent")

#pragma dylib(libxi, "libXi.so.6")
#pragma binding(libxi::XISelectEvents, "XISelectEvents")

#endif /* RGFW_X11_LINK_H */
