use alloc::string::String;
use alloc::vec::Vec;

use super::preprocessor::DylibSpec;

/// A pointer-to-global initializer that needs run-time
/// relocation. `data_offset` is the byte offset within
/// [`Program::data`] where the absolute address of the target
/// must end up at runtime; `target_offset` is the byte offset
/// of the target within the same data segment.
#[derive(Debug, Clone, Copy)]
pub struct DataReloc {
    /// Byte offset in `Program::data` of the 8-byte slot that
    /// holds the runtime address of `target_offset`. Always
    /// 8-byte aligned (c5 lays globals out in 8-byte slots).
    pub data_offset: u64,
    /// Byte offset in `Program::data` of the global being
    /// pointed at. Same data segment; cross-segment
    /// relocations (e.g., into `tls_data`) are future work.
    pub target_offset: u64,
}

/// Compiled program ready for the VM.
///
/// `text` holds the bytecode, `data` is the static data segment (string
/// literals plus zero-initialised globals), `entry_pc` points at the
/// first instruction of `main` inside `text`, and `warnings` carries
/// any non-fatal diagnostics the compiler emitted (type mismatches,
/// arity issues). The compiler never fails on a warning -- callers
/// decide whether to print, ignore, or treat them as errors.
///
/// `data_imm_positions` is a side channel for the native codegen: each
/// entry is a bytecode index where an `Op::Imm` operand holds an
/// offset into `data` (a string-literal address or a global-variable
/// address). The VM ignores it -- pointers are just integers there --
/// but the native backend needs to relocate these into __DATA's actual
/// load address, and there's no way to recover that distinction by
/// inspecting the bytecode alone (data offsets and plain integer
/// constants are indistinguishable).
#[derive(Debug, Clone)]
pub struct Program {
    pub text: Vec<i64>,
    pub data: Vec<u8>,
    pub entry_pc: usize,
    pub warnings: Vec<String>,
    pub data_imm_positions: Vec<usize>,
    /// For each `Op::JsrExt` whose call has any floating-point
    /// argument, record the call's bytecode PC and a bitmap of
    /// which arg positions are FP scalars (low bit = arg 0). The
    /// codegen reads this so it can route FP args through the
    /// platform's FP-arg registers (XMM0..7 on SysV / Win64,
    /// V0..V7 on AAPCS64) instead of the integer-arg path which
    /// currently funnels everything as raw 8-byte words. Calls
    /// with no FP args don't appear here -- absence is "all
    /// integer", which keeps the per-call lookup cheap.
    pub call_fp_arg_masks: Vec<(usize, u32)>,
    /// Initialised + zero-init thread-local data. Layout matches
    /// the way `data` does for ordinary globals: a flat byte array
    /// indexed by `Op::TlsLea`'s operand. The image writers copy
    /// this into `.tdata` (initialised slice = `tls_data[..tls_init_size]`)
    /// and `.tbss` (zero-fill remainder = `tls_data[tls_init_size..]`).
    /// Today everything starts zero (no `_Thread_local int x = 5;`
    /// initialiser syntax), so `tls_init_size == 0` and the whole
    /// block lives in .tbss; the layout is structured for future
    /// expansion.
    pub tls_data: Vec<u8>,
    /// Number of bytes of `tls_data` that are statically initialised
    /// (i.e., emitted into `.tdata`). The remainder
    /// (`tls_data.len() - tls_init_size` bytes) is zero-init and
    /// goes into `.tbss`. Invariant: `tls_init_size <= tls_data.len()`.
    pub tls_init_size: usize,
    /// Address-of-global initializers. Each entry says "byte
    /// `data_offset` of the data segment must hold the runtime
    /// address of byte `target_offset` of the data segment".
    /// Generated by initializers like
    /// `int *p = &x;` where both `p` and `x` live in `.data`.
    /// The VM ignores this -- it materializes pointers
    /// dynamically via `Op::Imm <offset>; <Add data_base>`. The
    /// native writers translate each entry to the per-format
    /// dynamic relocation:
    ///
    /// * **ELF** (`ET_EXEC`, no slide): write the absolute VA
    ///   into `build.data` at write time. No runtime fixup.
    /// * **Mach-O** (`MH_PIE`, slid): emit a rebase opcode for
    ///   the slot. Initial bytes hold the preferred VA; the
    ///   loader adds the slide.
    /// * **PE** (DYNAMIC_BASE + `.reloc`): emit a
    ///   `IMAGE_REL_BASED_DIR64` entry. Initial bytes hold the
    ///   preferred VA; the loader adds the slide delta.
    pub data_relocs: Vec<DataReloc>,
    /// Per-target dylib + binding map produced by the preprocessor
    /// from the `#pragma comment(dylib, ...)` and
    /// `#pragma binding(...)` directives in `headers/badc-{target}.h`.
    /// The native codegen uses this to:
    /// * pick the per-target real-symbol name for each c4 op
    ///   (`printf` -> `_printf` on macOS, `_printf` on Windows
    ///   msvcrt, `printf` on Linux),
    /// * conditionally include only those dylibs whose bindings the
    ///   program actually references (so a c5 source that never
    ///   calls `mprotect` doesn't drag `kernel32.dll` into the
    ///   import table on Windows), and
    /// * emit a hard error when a referenced op has no binding for
    ///   the chosen target, or when a declared dylib path doesn't
    ///   exist on disk.
    ///
    /// The VM ignores this field; only `emit_native` reaches for it.
    pub(crate) dylibs: Vec<DylibSpec>,
}
