use alloc::string::String;
use alloc::vec::Vec;

use super::preprocessor::DylibSpec;

/// One `#pragma export(<name>)` resolved against the
/// compiled program: the externally visible name plus the
/// function's bytecode PC (i.e., the byte offset within
/// `Program::text` of the function's first instruction).
/// Shared-object writers map this to a per-format export
/// entry whose runtime address is `text_vmaddr + bytecode_pc`.
#[derive(Debug, Clone)]
pub struct ExportedFunction {
    /// External name as written in `#pragma export(...)`.
    /// Per-format writers may decorate it with a leading
    /// underscore (Mach-O `_foo`) at emit time; the c5-side
    /// name stays as the user wrote it.
    pub name: String,
    /// Bytecode PC of the function's first instruction. The
    /// writer translates this to a code-segment offset via
    /// `Build::bytecode_to_native`, then to a runtime address
    /// by adding the code segment's vmaddr base.
    pub bytecode_pc: usize,
}

/// A pointer-to-global initializer that needs run-time
/// relocation. `data_offset` is the byte offset within
/// [`Program::data`] where the absolute address of the target
/// must end up at runtime; `target_offset` is the byte offset
/// of the target within the same data segment.
#[derive(Debug, Clone, Copy)]
pub struct DataReloc {
    /// Byte offset in `Program::data` of the 8-byte slot that
    /// holds the runtime address of `target_offset`. Always
    /// 8-byte aligned (c5 lays globals out in 8-byte slots).
    pub data_offset: u64,
    /// Byte offset in `Program::data` of the global being
    /// pointed at. Same data segment; cross-segment
    /// relocations (e.g., into `tls_data`) are future work.
    pub target_offset: u64,
}

/// A function-pointer initializer that needs run-time relocation.
/// `data_offset` is the byte offset within [`Program::data`] where
/// the function's runtime code address must end up; `target_bc_pc`
/// is the function's bytecode PC (resolved by the codegen via
/// `Build::bytecode_to_native` to the native code-segment offset,
/// then to a runtime address by adding the text segment's vmaddr).
///
/// Generated by initializers like
/// `static const VTable v = { .xClose = my_close };`. The VM
/// reads the data slot directly because its function pointers
/// carry the small `CODE_BASE + bc_pc` bias and `Op::Jsri`
/// recognises that range. Native writers replace the slot's
/// contents at write time (ELF) or via a dynamic relocation
/// (Mach-O rebase, PE `.reloc DIR64`).
#[derive(Debug, Clone, Copy)]
pub struct CodeReloc {
    /// Byte offset in `Program::data` of the 8-byte slot that
    /// receives the function's runtime code address. Always
    /// 8-byte aligned.
    pub data_offset: u64,
    /// Bytecode PC of the function. The codegen translates this
    /// to a native code-segment offset via `bytecode_to_native`.
    pub target_bc_pc: u64,
}

/// Compiled program ready for the VM.
///
/// `text` holds the bytecode, `data` is the static data segment (string
/// literals plus zero-initialised globals), `entry_pc` points at the
/// first instruction of `main` inside `text`, and `warnings` carries
/// any non-fatal diagnostics the compiler emitted (type mismatches,
/// arity issues). The compiler never fails on a warning -- callers
/// decide whether to print, ignore, or treat them as errors.
///
/// `data_imm_positions` is a side channel for the native codegen: each
/// entry is a bytecode index where an `Op::Imm` operand holds an
/// offset into `data` (a string-literal address or a global-variable
/// address). The VM ignores it -- pointers are just integers there --
/// but the native backend needs to relocate these into __DATA's actual
/// load address, and there's no way to recover that distinction by
/// inspecting the bytecode alone (data offsets and plain integer
/// constants are indistinguishable).
#[derive(Debug, Clone)]
pub struct Program {
    pub text: Vec<i64>,
    pub data: Vec<u8>,
    pub entry_pc: usize,
    pub warnings: Vec<String>,
    pub data_imm_positions: Vec<usize>,
    /// Mirror of `data_imm_positions` for function-pointer
    /// literals: each entry is a bytecode index whose `Op::Imm`
    /// operand holds (CODE_BASE + bc_pc) -- i.e. the address of
    /// a function. Without this list the native codegen would
    /// have to guess from the value alone, and any user constant
    /// that happens to fall in the [CODE_BASE, CODE_BASE +
    /// text.len()) range would be misclassified as a function
    /// pointer (e.g. `0x20000000` clashes with CODE_BASE
    /// exactly). The compiler records every func-ptr-Imm
    /// operand_pc here so the codegen knows precisely which Imm
    /// values to treat as function addresses.
    pub code_imm_positions: Vec<usize>,
    /// For each `Op::JsrExt` whose call has any floating-point
    /// argument, record the call's bytecode PC and a bitmap of
    /// which arg positions are FP scalars (low bit = arg 0). The
    /// codegen reads this so it can route FP args through the
    /// platform's FP-arg registers (XMM0..7 on SysV / Win64,
    /// V0..V7 on AAPCS64) instead of the integer-arg path which
    /// currently funnels everything as raw 8-byte words. Calls
    /// with no FP args don't appear here -- absence is "all
    /// integer", which keeps the per-call lookup cheap.
    pub call_fp_arg_masks: Vec<(usize, u32)>,
    /// Initialised + zero-init thread-local data. Layout matches
    /// the way `data` does for ordinary globals: a flat byte array
    /// indexed by `Op::TlsLea`'s operand. The image writers copy
    /// this into `.tdata` (initialised slice = `tls_data[..tls_init_size]`)
    /// and `.tbss` (zero-fill remainder = `tls_data[tls_init_size..]`).
    /// Today everything starts zero (no `_Thread_local int x = 5;`
    /// initialiser syntax), so `tls_init_size == 0` and the whole
    /// block lives in .tbss; the layout is structured for future
    /// expansion.
    pub tls_data: Vec<u8>,
    /// Number of bytes of `tls_data` that are statically initialised
    /// (i.e., emitted into `.tdata`). The remainder
    /// (`tls_data.len() - tls_init_size` bytes) is zero-init and
    /// goes into `.tbss`. Invariant: `tls_init_size <= tls_data.len()`.
    pub tls_init_size: usize,
    /// Address-of-global initializers. Each entry says "byte
    /// `data_offset` of the data segment must hold the runtime
    /// address of byte `target_offset` of the data segment".
    /// Generated by initializers like
    /// `int *p = &x;` where both `p` and `x` live in `.data`.
    /// The VM ignores this -- it materializes pointers
    /// dynamically via `Op::Imm <offset>; <Add data_base>`. The
    /// native writers translate each entry to the per-format
    /// dynamic relocation:
    ///
    /// * **ELF** (`ET_EXEC`, no slide): write the absolute VA
    ///   into `build.data` at write time. No runtime fixup.
    /// * **Mach-O** (`MH_PIE`, slid): emit a rebase opcode for
    ///   the slot. Initial bytes hold the preferred VA; the
    ///   loader adds the slide.
    /// * **PE** (DYNAMIC_BASE + `.reloc`): emit a
    ///   `IMAGE_REL_BASED_DIR64` entry. Initial bytes hold the
    ///   preferred VA; the loader adds the slide delta.
    pub data_relocs: Vec<DataReloc>,
    /// Function-pointer initializers in the data segment. Each
    /// entry says "byte `data_offset` of the data segment must
    /// hold the runtime code address of the function whose first
    /// instruction is at bytecode PC `target_bc_pc`". Per-format
    /// writer handling mirrors `data_relocs` -- see [`CodeReloc`]
    /// for the per-format strategy.
    pub code_relocs: Vec<CodeReloc>,
    /// Functions the program asked to expose externally via
    /// `#pragma export(<name>)`. Each entry pairs the source
    /// name with the function's bytecode PC -- the
    /// shared-object writers (Mach-O dylib, ELF .so, PE DLL)
    /// promote each entry to a real export-table record so
    /// callers in another image can resolve the symbol via
    /// `dlsym` / `GetProcAddress`.
    ///
    /// Empty for executable output (the user-supplied
    /// program never reached for `#pragma export`, or the
    /// build asked for an executable rather than a shared
    /// library). The VM and JIT ignore this field; only the
    /// shared-object writer paths consume it.
    pub exports: Vec<ExportedFunction>,
    /// Per-target dylib + binding map produced by the preprocessor
    /// from the `#pragma comment(dylib, ...)` and
    /// `#pragma binding(...)` directives in `headers/badc-{target}.h`.
    /// The native codegen uses this to:
    /// * pick the per-target real-symbol name for each c4 op
    ///   (`printf` -> `_printf` on macOS, `_printf` on Windows
    ///   msvcrt, `printf` on Linux),
    /// * conditionally include only those dylibs whose bindings the
    ///   program actually references (so a c5 source that never
    ///   calls `mprotect` doesn't drag `kernel32.dll` into the
    ///   import table on Windows), and
    /// * emit a hard error when a referenced op has no binding for
    ///   the chosen target, or when a declared dylib path doesn't
    ///   exist on disk.
    ///
    /// The VM ignores this field; only `emit_native` reaches for it.
    pub(crate) dylibs: Vec<DylibSpec>,
    /// Bytecode PC of a user-defined `DllMain` function, if the
    /// source declared one. Used by the PE writer for
    /// `--shared` output: when present, `AddressOfEntryPoint`
    /// targets the user's body and the boilerplate
    /// `mov eax, 1; ret` stub is suppressed; when `None`, the
    /// writer falls back to the stub. The signature isn't
    /// validated -- the user is trusted to honor the Win64
    /// `BOOL DllMain(HINSTANCE, DWORD, LPVOID)` shape, same as
    /// `main` is trusted today. The Mach-O / ELF / VM / JIT
    /// paths ignore this field.
    pub dllmain_pc: Option<usize>,
    /// Source-line debug map. Indexed by bytecode PC; each entry
    /// is the 1-based source line of the C statement / expression
    /// that produced this op. Operand slots inherit their op's
    /// line. Unknown / unmapped entries are 0.
    ///
    /// Surfaced by `--dump-asm` as a `; line N` comment next to
    /// each op so codegen failures can be traced back to a
    /// specific C line, and exposed structurally by the
    /// `bytecode_pc_to_line` helper for runtime crash reporters.
    pub source_lines: Vec<u32>,
    /// Source-function debug map. Same indexing as `source_lines`;
    /// each entry is the name of the C function whose body the op
    /// belongs to (empty string for top-level data emission).
    pub source_functions: Vec<String>,
    /// Source-file table indexed by `source_file_indices`. Populated
    /// by the lexer's GNU line-marker handling: each `#include`
    /// boundary or `#line N "file"` directive interns a fresh
    /// filename. Index 0 is the user's translation-unit source
    /// (the `--source-path` CLI arg, falling back to the lexer's
    /// initial `"<source>"` placeholder).
    pub source_files: Vec<String>,
    /// Per-PC index into `source_files`. Same indexing as
    /// `source_lines`. The DWARF line program walks this to emit
    /// `DW_LNS_set_file` at every transition so `lldb image lookup`
    /// reports the *header*'s name when the PC came from a header,
    /// not the user's translation-unit file.
    pub source_file_indices: Vec<u16>,
    /// Filesystem path of the input `.c` file, when known. Set by
    /// the CLI shim from the user's argv before
    /// [`crate::emit_native`] runs; the c5 frontend itself doesn't
    /// know the path, so it leaves this empty for the
    /// `compile_str` / stdin / fixture paths.
    ///
    /// The DWARF emitter uses this as the CU's
    /// `DW_AT_name` and the line program's only file entry, so
    /// `lldb image lookup -n foo` reports `foo at /path/to/src.c:N`
    /// instead of `<unknown>:N`. Empty falls back to `<unknown>`.
    /// The VM / JIT / interpreter ignore it.
    pub source_path: String,
    /// Per-function local + formal-parameter records, captured at
    /// function-body close (just before the c5 `Token::Loc`
    /// shadowing is unwound). Indexed by lookup -- consumers
    /// (DWARF emitter) filter by `function_bc_pc` to gather
    /// the variables that belong to each subprogram.
    ///
    /// `fp_slot` is the c5 frame-relative slot the symbol resolves
    /// to: positive values are arguments (`fp + slot*8`, which is
    /// `fp+0x10` for the first arg etc.), negative values are
    /// locals (`fp + slot*8`, e.g. `-1` -> `fp - 8`). DWARF turns
    /// this into a `DW_AT_location` with `DW_OP_fbreg` so lldb /
    /// gdb can resolve a variable name to its current stack
    /// address.
    ///
    /// Empty when c5 is run as a library (no driver-side capture)
    /// or the program contains no functions. The VM / JIT /
    /// interpreter ignore this field.
    pub variables: Vec<VariableInfo>,
    /// Struct / union registry, indexed by the struct id encoded
    /// in c5 type tags (`STRUCT_BASE + id * STRUCT_STRIDE`).
    /// Cloned out of `Compiler::structs` at `compile()` time so
    /// the DWARF emitter can walk member offsets and
    /// bitfield layouts to produce `DW_TAG_structure_type` /
    /// `DW_TAG_union_type` DIEs. The VM / JIT / interpreter
    /// ignore this field.
    pub structs: Vec<crate::c5::compiler::StructDef>,
    /// Source-declared entry-point name. Set by
    /// `#pragma entrypoint(<name>)`; `None` falls back to the
    /// canonical `main`. The compile pass already used the
    /// override to compute `entry_pc`; this field carries the
    /// name forward so the PE writer (and any future image
    /// writer that wants the symbol name in the export table)
    /// can name the entry symbol correctly. The VM / JIT
    /// resolve through `entry_pc` directly and ignore this
    /// field.
    pub entry_name: Option<String>,
    /// Source-declared Windows subsystem. Set by
    /// `#pragma subsystem(<kind>)`; `None` falls back to the
    /// PE writer's default (`Console`). Read only by the PE
    /// writers; non-PE targets (Mach-O / ELF) ignore this
    /// field.
    pub subsystem: Option<crate::c5::preprocessor::Subsystem>,
}

/// A single local variable or formal parameter belonging to a
/// specific c5-emitted function, captured for DWARF emission.
/// The function is identified by `function_bc_pc` --
/// the bytecode PC of its `Op::Ent`, which the DWARF emitter
/// already uses to find the matching subprogram DIE.
#[derive(Debug, Clone)]
pub struct VariableInfo {
    /// Bytecode PC of the owning function's `Op::Ent`. Same value
    /// the subprogram-discovery walk in `dwarf::collect_subprograms`
    /// produces, so the DWARF emitter can group variables by
    /// subprogram with a simple equality check.
    pub function_bc_pc: u64,
    /// Source-level identifier (parameter or local name).
    pub name: String,
    /// c5 type tag (`Ty` enum encoded as `i64`). Pointer levels
    /// follow the `+= 2` convention; struct types live in the
    /// `STRUCT_BASE +` band.
    pub type_tag: i64,
    /// Frame-relative slot. `>=2` is an argument (caller pushed
    /// it at `fp + slot*8`); `<0` is a local (the function
    /// allocated it at `fp + slot*8`, with the value negative).
    /// Slots `0..2` are the saved-x29 / saved-x30 area and don't
    /// hold user-visible variables.
    pub fp_slot: i64,
    /// True for arguments (`Token::Loc` symbols introduced by the
    /// parameter list) so the DWARF emitter picks
    /// `DW_TAG_formal_parameter`; locals get `DW_TAG_variable`.
    pub is_parameter: bool,
}
