// @generated by tools/gen_isa_a64.py from an external instruction-set
// database. Do not edit by hand; re-run the generator to update.
//
// The A64 GP catalogue interpreted by `super::table::encode`: every
// database row whose written-operand signature maps onto the field
// model. Seven database rows are corrected and two dropped before
// parsing (see tools/gen_isa_a64.py DB_FIXES / EXCLUDED_ROWS).

use super::table::{A64Op, A64Op::*, Field, Field::*, Form};

#[rustfmt::skip]
pub(crate) static FORMS: &[Form] = &[
    Form { mnemonic: "abs", ops: &[W, W], base: 0x5AC02000, fields: &[Rd, Rn] },  // abs Wd, Wn
    Form { mnemonic: "abs", ops: &[X, X], base: 0xDAC02000, fields: &[Rd, Rn] },  // abs Xd, Xn
    Form { mnemonic: "adc", ops: &[W, W, W], base: 0x1A000000, fields: &[Rd, Rn, Rm] },  // adc Wd, Wn, Wm
    Form { mnemonic: "adc", ops: &[X, X, X], base: 0x9A000000, fields: &[Rd, Rn, Rm] },  // adc Xd, Xn, Xm
    Form { mnemonic: "adcs", ops: &[W, W, W], base: 0x3A000000, fields: &[Rd, Rn, Rm] },  // adcs Wd, Wn, Wm
    Form { mnemonic: "adcs", ops: &[X, X, X], base: 0xBA000000, fields: &[Rd, Rn, Rm] },  // adcs Xd, Xn, Xm
    Form { mnemonic: "add", ops: &[W, W, W], base: 0x0B000000, fields: &[Rd, Rn, Rm] },  // add Wd, Wn, Wm, {lsl|lsr|asr #n}
    Form { mnemonic: "add", ops: &[X, X, X], base: 0x8B000000, fields: &[Rd, Rn, Rm] },  // add Xd, Xn, Xm, {lsl|lsr|asr #n}
    Form { mnemonic: "add", ops: &[W, W, Imm], base: 0x11000000, fields: &[Rd, Rn, UImm { op: 2, shift: 10, width: 12 }] },  // add Wd|WSP, Wn|WSP, #immZ, {lsl #n=0|12}
    Form { mnemonic: "add", ops: &[X, X, Imm], base: 0x91000000, fields: &[Rd, Rn, UImm { op: 2, shift: 10, width: 12 }] },  // add Xd|SP, Xn|SP, #immZ, {lsl #n=0|12}
    Form { mnemonic: "addpt", ops: &[X, X, X], base: 0x9A002000, fields: &[Rd, Rn, Rm] },  // addpt Xd|SP, Xn|SP, Xm, {lsl #n}
    Form { mnemonic: "adds", ops: &[W, W, W], base: 0x2B000000, fields: &[Rd, Rn, Rm] },  // adds Wd, Wn, Wm, {lsl|lsr|asr #n}
    Form { mnemonic: "adds", ops: &[X, X, X], base: 0xAB000000, fields: &[Rd, Rn, Rm] },  // adds Xd, Xn, Xm, {lsl|lsr|asr #n}
    Form { mnemonic: "adds", ops: &[W, W, Imm], base: 0x31000000, fields: &[Rd, Rn, UImm { op: 2, shift: 10, width: 12 }] },  // adds Wd|WSP, Wn|WSP, #immZ, {lsl #n=0|12}
    Form { mnemonic: "adds", ops: &[X, X, Imm], base: 0xB1000000, fields: &[Rd, Rn, UImm { op: 2, shift: 10, width: 12 }] },  // adds Xd|SP, Xn|SP, #immZ, {lsl #n=0|12}
    Form { mnemonic: "and", ops: &[W, W, W], base: 0x0A000000, fields: &[Rd, Rn, Rm] },  // and Wd|WSP, Wn, Wm, {sop #n}
    Form { mnemonic: "and", ops: &[X, X, X], base: 0x8A000000, fields: &[Rd, Rn, Rm] },  // and Xd|SP, Xn, Xm, {sop #n}
    Form { mnemonic: "and", ops: &[W, W, Imm], base: 0x12000000, fields: &[Rd, Rn, LogicalImm { op: 2, is64: false }] },  // and Wd|WSP, Wn, #imm
    Form { mnemonic: "and", ops: &[X, X, Imm], base: 0x92000000, fields: &[Rd, Rn, LogicalImm { op: 2, is64: true }] },  // and Xd|SP, Xn, #imm
    Form { mnemonic: "ands", ops: &[W, W, W], base: 0x6A000000, fields: &[Rd, Rn, Rm] },  // ands Wd|WSP, Wn, Wm, {sop #n}
    Form { mnemonic: "ands", ops: &[X, X, X], base: 0xEA000000, fields: &[Rd, Rn, Rm] },  // ands Xd|SP, Xn, Xm, {sop #n}
    Form { mnemonic: "ands", ops: &[W, W, Imm], base: 0x72000000, fields: &[Rd, Rn, LogicalImm { op: 2, is64: false }] },  // ands Wd|WSP, Wn, #imm
    Form { mnemonic: "ands", ops: &[X, X, Imm], base: 0xF2000000, fields: &[Rd, Rn, LogicalImm { op: 2, is64: true }] },  // ands Xd|SP, Xn, #imm
    Form { mnemonic: "asr", ops: &[W, W, W], base: 0x1AC02800, fields: &[Rd, Rn, Rm] },  // asr|asrv Wd, Wn, Wm
    Form { mnemonic: "asr", ops: &[X, X, X], base: 0x9AC02800, fields: &[Rd, Rn, Rm] },  // asr|asrv Xd, Xn, Xm
    Form { mnemonic: "asr", ops: &[W, W, Imm], base: 0x13007C00, fields: &[Rd, Rn, ShrAlias { op: 2 }] },  // asr Wd, Wn, #n
    Form { mnemonic: "asr", ops: &[X, X, Imm], base: 0x9340FC00, fields: &[Rd, Rn, ShrAlias { op: 2 }] },  // asr Xd, Xn, #n
    Form { mnemonic: "asrv", ops: &[W, W, W], base: 0x1AC02800, fields: &[Rd, Rn, Rm] },  // asr|asrv Wd, Wn, Wm
    Form { mnemonic: "asrv", ops: &[X, X, X], base: 0x9AC02800, fields: &[Rd, Rn, Rm] },  // asr|asrv Xd, Xn, Xm
    Form { mnemonic: "autda", ops: &[X, X], base: 0xDAC11800, fields: &[Rd, Rn] },  // autda Xd, Xn|SP
    Form { mnemonic: "autdb", ops: &[X, X], base: 0xDAC11C00, fields: &[Rd, Rn] },  // autdb Xd, Xn|SP
    Form { mnemonic: "autdza", ops: &[X], base: 0xDAC13BE0, fields: &[Rd] },  // autdza Xd
    Form { mnemonic: "autdzb", ops: &[X], base: 0xDAC13FE0, fields: &[Rd] },  // autdzb Xd
    Form { mnemonic: "autia", ops: &[X, X], base: 0xDAC11000, fields: &[Rd, Rn] },  // autia Xd, Xn|SP
    Form { mnemonic: "autia1716", ops: &[], base: 0xD503219F, fields: &[] },  // autia1716
    Form { mnemonic: "autiasp", ops: &[], base: 0xD50323BF, fields: &[] },  // autiasp
    Form { mnemonic: "autiaz", ops: &[], base: 0xD503239F, fields: &[] },  // autiaz
    Form { mnemonic: "autib", ops: &[X, X], base: 0xDAC11400, fields: &[Rd, Rn] },  // autib Xd, Xn|SP
    Form { mnemonic: "autib1716", ops: &[], base: 0xD50321DF, fields: &[] },  // autib1716
    Form { mnemonic: "autibsp", ops: &[], base: 0xD50323FF, fields: &[] },  // autibsp
    Form { mnemonic: "autibz", ops: &[], base: 0xD50323DF, fields: &[] },  // autibz
    Form { mnemonic: "autiza", ops: &[X], base: 0xDAC133E0, fields: &[Rd] },  // autiza Xd
    Form { mnemonic: "autizb", ops: &[X], base: 0xDAC137E0, fields: &[Rd] },  // autizb Xd
    Form { mnemonic: "axflag", ops: &[], base: 0xD500405F, fields: &[] },  // axflag
    Form { mnemonic: "bic", ops: &[W, W, W], base: 0x0A200000, fields: &[Rd, Rn, Rm] },  // bic Wd, Wn, Wm, {sop #n}
    Form { mnemonic: "bic", ops: &[X, X, X], base: 0x8A200000, fields: &[Rd, Rn, Rm] },  // bic Xd, Xn, Xm, {sop #n}
    Form { mnemonic: "bics", ops: &[W, W, W], base: 0x6A200000, fields: &[Rd, Rn, Rm] },  // bics Wd, Wn, Wm, {sop #n}
    Form { mnemonic: "bics", ops: &[X, X, X], base: 0xEA200000, fields: &[Rd, Rn, Rm] },  // bics Xd, Xn, Xm, {sop #n}
    Form { mnemonic: "brk", ops: &[Imm], base: 0xD4200000, fields: &[UImm { op: 0, shift: 5, width: 16 }] },  // brk #imm
    Form { mnemonic: "cfinv", ops: &[], base: 0xD500401F, fields: &[] },  // cfinv
    Form { mnemonic: "chkfeat", ops: &[], base: 0xD503251F, fields: &[] },  // chkfeat
    Form { mnemonic: "clrbhb", ops: &[], base: 0xD50322DF, fields: &[] },  // clrbhb
    Form { mnemonic: "cls", ops: &[W, W], base: 0x5AC01400, fields: &[Rd, Rn] },  // cls Wd, Wn
    Form { mnemonic: "cls", ops: &[X, X], base: 0xDAC01400, fields: &[Rd, Rn] },  // cls Xd, Xn
    Form { mnemonic: "clz", ops: &[W, W], base: 0x5AC01000, fields: &[Rd, Rn] },  // clz Wd, Wn
    Form { mnemonic: "clz", ops: &[X, X], base: 0xDAC01000, fields: &[Rd, Rn] },  // clz Xd, Xn
    Form { mnemonic: "cnt", ops: &[W, W], base: 0x5AC01C00, fields: &[Rd, Rn] },  // cnt Wd, Wn
    Form { mnemonic: "cnt", ops: &[X, X], base: 0xDAC01C00, fields: &[Rd, Rn] },  // cnt Xd, Xn
    Form { mnemonic: "crc32b", ops: &[W, W, W], base: 0x1AC04000, fields: &[Rd, Rn, Rm] },  // crc32b Wd, Wn, Wm
    Form { mnemonic: "crc32cb", ops: &[W, W, W], base: 0x1AC05000, fields: &[Rd, Rn, Rm] },  // crc32cb Wd, Wn, Wm
    Form { mnemonic: "crc32ch", ops: &[W, W, W], base: 0x1AC05400, fields: &[Rd, Rn, Rm] },  // crc32ch Wd, Wn, Wm
    Form { mnemonic: "crc32cw", ops: &[W, W, W], base: 0x1AC05800, fields: &[Rd, Rn, Rm] },  // crc32cw Wd, Wn, Wm
    Form { mnemonic: "crc32cx", ops: &[W, W, X], base: 0x9AC05C00, fields: &[Rd, Rn, Rm] },  // crc32cx Wd, Wn, Xm
    Form { mnemonic: "crc32h", ops: &[W, W, W], base: 0x1AC04400, fields: &[Rd, Rn, Rm] },  // crc32h Wd, Wn, Wm
    Form { mnemonic: "crc32w", ops: &[W, W, W], base: 0x1AC04800, fields: &[Rd, Rn, Rm] },  // crc32w Wd, Wn, Wm
    Form { mnemonic: "crc32x", ops: &[W, W, X], base: 0x9AC04C00, fields: &[Rd, Rn, Rm] },  // crc32x Wd, Wn, Xm
    Form { mnemonic: "csdb", ops: &[], base: 0xD503229F, fields: &[] },  // csdb
    Form { mnemonic: "csel", ops: &[W, W, W, A64Op::Cond], base: 0x1A800000, fields: &[Rd, Rn, Rm, Field::Cond { op: 3, inv: false }] },  // csel Wd, Wn, Wm, #cond
    Form { mnemonic: "csel", ops: &[X, X, X, A64Op::Cond], base: 0x9A800000, fields: &[Rd, Rn, Rm, Field::Cond { op: 3, inv: false }] },  // csel Xd, Xn, Xm, #cond
    Form { mnemonic: "cset", ops: &[W, A64Op::Cond], base: 0x1A9F07E0, fields: &[Rd, Field::Cond { op: 1, inv: true }] },  // cset Wd, #cond
    Form { mnemonic: "cset", ops: &[X, A64Op::Cond], base: 0x9A9F07E0, fields: &[Rd, Field::Cond { op: 1, inv: true }] },  // cset Xd, #cond
    Form { mnemonic: "csetm", ops: &[W, A64Op::Cond], base: 0x5A9F03E0, fields: &[Rd, Field::Cond { op: 1, inv: true }] },  // csetm Wd, #cond
    Form { mnemonic: "csetm", ops: &[X, A64Op::Cond], base: 0xDA9F03E0, fields: &[Rd, Field::Cond { op: 1, inv: true }] },  // csetm Xd, #cond
    Form { mnemonic: "csinc", ops: &[W, W, W, A64Op::Cond], base: 0x1A800400, fields: &[Rd, Rn, Rm, Field::Cond { op: 3, inv: false }] },  // csinc Wd, Wn, Wm, #cond
    Form { mnemonic: "csinc", ops: &[X, X, X, A64Op::Cond], base: 0x9A800400, fields: &[Rd, Rn, Rm, Field::Cond { op: 3, inv: false }] },  // csinc Xd, Xn, Xm, #cond
    Form { mnemonic: "csinv", ops: &[W, W, W, A64Op::Cond], base: 0x5A800000, fields: &[Rd, Rn, Rm, Field::Cond { op: 3, inv: false }] },  // csinv Wd, Wn, Wm, #cond
    Form { mnemonic: "csinv", ops: &[X, X, X, A64Op::Cond], base: 0xDA800000, fields: &[Rd, Rn, Rm, Field::Cond { op: 3, inv: false }] },  // csinv Xd, Xn, Xm, #cond
    Form { mnemonic: "csneg", ops: &[W, W, W, A64Op::Cond], base: 0x5A800400, fields: &[Rd, Rn, Rm, Field::Cond { op: 3, inv: false }] },  // csneg Wd, Wn, Wm, #cond
    Form { mnemonic: "csneg", ops: &[X, X, X, A64Op::Cond], base: 0xDA800400, fields: &[Rd, Rn, Rm, Field::Cond { op: 3, inv: false }] },  // csneg Xd, Xn, Xm, #cond
    Form { mnemonic: "ctz", ops: &[W, W], base: 0x5AC01800, fields: &[Rd, Rn] },  // ctz Wd, Wn
    Form { mnemonic: "ctz", ops: &[X, X], base: 0xDAC01800, fields: &[Rd, Rn] },  // ctz Xd, Xn
    Form { mnemonic: "dgh", ops: &[], base: 0xD50320DF, fields: &[] },  // dgh
    Form { mnemonic: "drps", ops: &[], base: 0xD6BF03E0, fields: &[] },  // drps
    Form { mnemonic: "eon", ops: &[W, W, W], base: 0x4A200000, fields: &[Rd, Rn, Rm] },  // eon Wd, Wn, Wm, {sop #n}
    Form { mnemonic: "eon", ops: &[X, X, X], base: 0xCA200000, fields: &[Rd, Rn, Rm] },  // eon Xd, Xn, Xm, {sop #n}
    Form { mnemonic: "eor", ops: &[W, W, W], base: 0x4A000000, fields: &[Rd, Rn, Rm] },  // eor Wd, Wn, Wm, {sop #n}
    Form { mnemonic: "eor", ops: &[X, X, X], base: 0xCA000000, fields: &[Rd, Rn, Rm] },  // eor Xd, Xn, Xm, {sop #n}
    Form { mnemonic: "eor", ops: &[W, W, Imm], base: 0x52000000, fields: &[Rd, Rn, LogicalImm { op: 2, is64: false }] },  // eor Wd|WSP, Wn, #imm
    Form { mnemonic: "eor", ops: &[X, X, Imm], base: 0xD2000000, fields: &[Rd, Rn, LogicalImm { op: 2, is64: true }] },  // eor Xd|SP, Xn, #imm
    Form { mnemonic: "eret", ops: &[], base: 0xD69F03E0, fields: &[] },  // eret
    Form { mnemonic: "eretaa", ops: &[], base: 0xD69F0BFF, fields: &[] },  // eretaa
    Form { mnemonic: "eretab", ops: &[], base: 0xD69F0FFF, fields: &[] },  // eretab
    Form { mnemonic: "esb", ops: &[], base: 0xD503221F, fields: &[] },  // esb
    Form { mnemonic: "extr", ops: &[W, W, W, Imm], base: 0x13800000, fields: &[Rd, Rn, Rm, UImm { op: 3, shift: 10, width: 5 }] },  // extr Wd, Wn, Wm, #imm
    Form { mnemonic: "extr", ops: &[X, X, X, Imm], base: 0x93C00000, fields: &[Rd, Rn, Rm, UImm { op: 3, shift: 10, width: 6 }] },  // extr Xd, Xn, Xm, #imm
    Form { mnemonic: "gcspopcx", ops: &[], base: 0xD50877BF, fields: &[] },  // gcspopcx
    Form { mnemonic: "gcspopx", ops: &[], base: 0xD50877DF, fields: &[] },  // gcspopx
    Form { mnemonic: "gcspushx", ops: &[], base: 0xD508779F, fields: &[] },  // gcspushx
    Form { mnemonic: "gmi", ops: &[X, X, X], base: 0x9AC01400, fields: &[Rd, Rn, Rm] },  // gmi Xd, Xn|SP, Xm
    Form { mnemonic: "hint", ops: &[Imm], base: 0xD503201F, fields: &[UImm { op: 0, shift: 5, width: 7 }] },  // hint #imm
    Form { mnemonic: "hlt", ops: &[Imm], base: 0xD4400000, fields: &[UImm { op: 0, shift: 5, width: 16 }] },  // hlt #imm
    Form { mnemonic: "hvc", ops: &[Imm], base: 0xD4000002, fields: &[UImm { op: 0, shift: 5, width: 16 }] },  // hvc #imm
    Form { mnemonic: "irg", ops: &[X, X, X], base: 0x9AC01000, fields: &[Rd, Rn, Rm] },  // irg Xd, Xn|SP, Xm
    Form { mnemonic: "lsl", ops: &[W, W, W], base: 0x1AC02000, fields: &[Rd, Rn, Rm] },  // lsl|lslv Wd, Wn, Wm
    Form { mnemonic: "lsl", ops: &[X, X, X], base: 0x9AC02000, fields: &[Rd, Rn, Rm] },  // lsl|lslv Xd, Xn, Xm
    Form { mnemonic: "lsl", ops: &[W, W, Imm], base: 0x53000000, fields: &[Rd, Rn, LslAlias { op: 2, is64: false }] },  // lsl Wd, Wn, #n
    Form { mnemonic: "lsl", ops: &[X, X, Imm], base: 0xD3400000, fields: &[Rd, Rn, LslAlias { op: 2, is64: true }] },  // lsl Xd, Xn, #n
    Form { mnemonic: "lslv", ops: &[W, W, W], base: 0x1AC02000, fields: &[Rd, Rn, Rm] },  // lsl|lslv Wd, Wn, Wm
    Form { mnemonic: "lslv", ops: &[X, X, X], base: 0x9AC02000, fields: &[Rd, Rn, Rm] },  // lsl|lslv Xd, Xn, Xm
    Form { mnemonic: "lsr", ops: &[W, W, W], base: 0x1AC02400, fields: &[Rd, Rn, Rm] },  // lsr|lsrv Wd, Wn, Wm
    Form { mnemonic: "lsr", ops: &[X, X, X], base: 0x9AC02400, fields: &[Rd, Rn, Rm] },  // lsr|lsrv Xd, Xn, Xm
    Form { mnemonic: "lsr", ops: &[W, W, Imm], base: 0x53007C00, fields: &[Rd, Rn, ShrAlias { op: 2 }] },  // lsr Wd, Wn, #n
    Form { mnemonic: "lsr", ops: &[X, X, Imm], base: 0xD340FC00, fields: &[Rd, Rn, ShrAlias { op: 2 }] },  // lsr Xd, Xn, #n
    Form { mnemonic: "lsrv", ops: &[W, W, W], base: 0x1AC02400, fields: &[Rd, Rn, Rm] },  // lsr|lsrv Wd, Wn, Wm
    Form { mnemonic: "lsrv", ops: &[X, X, X], base: 0x9AC02400, fields: &[Rd, Rn, Rm] },  // lsr|lsrv Xd, Xn, Xm
    Form { mnemonic: "madd", ops: &[W, W, W, W], base: 0x1B000000, fields: &[Rd, Rn, Rm, Ra] },  // madd Wd, Wn, Wm, Wa
    Form { mnemonic: "madd", ops: &[X, X, X, X], base: 0x9B000000, fields: &[Rd, Rn, Rm, Ra] },  // madd Xd, Xn, Xm, Xa
    Form { mnemonic: "maddpt", ops: &[X, X, X, X], base: 0x9B600000, fields: &[Rd, Rn, Rm, Ra] },  // maddpt Xd, Xn, Xm, Xa
    Form { mnemonic: "mneg", ops: &[W, W, W], base: 0x1B00FC00, fields: &[Rd, Rn, Rm] },  // mneg Wd, Wn, Wm
    Form { mnemonic: "mneg", ops: &[X, X, X], base: 0x9B00FC00, fields: &[Rd, Rn, Rm] },  // mneg Xd, Xn, Xm
    Form { mnemonic: "movk", ops: &[W, Imm, OptLsl], base: 0x72800000, fields: &[Rd, MovImm { op: 1 }, MovHw { op: 2 }] },  // movk Wd, #imm, {lsl #n}
    Form { mnemonic: "movk", ops: &[X, Imm, OptLsl], base: 0xF2800000, fields: &[Rd, MovImm { op: 1 }, MovHw { op: 2 }] },  // movk Xd, #imm, {lsl #n}
    Form { mnemonic: "movn", ops: &[W, Imm, OptLsl], base: 0x12800000, fields: &[Rd, MovImm { op: 1 }, MovHw { op: 2 }] },  // movn Wd, #imm, {lsl #n}
    Form { mnemonic: "movn", ops: &[X, Imm, OptLsl], base: 0x92800000, fields: &[Rd, MovImm { op: 1 }, MovHw { op: 2 }] },  // movn Xd, #imm, {lsl #n}
    Form { mnemonic: "movz", ops: &[W, Imm, OptLsl], base: 0x52800000, fields: &[Rd, MovImm { op: 1 }, MovHw { op: 2 }] },  // movz Wd, #imm, {lsl #n}
    Form { mnemonic: "movz", ops: &[X, Imm, OptLsl], base: 0xD2800000, fields: &[Rd, MovImm { op: 1 }, MovHw { op: 2 }] },  // movz Xd, #imm, {lsl #n}
    Form { mnemonic: "msub", ops: &[W, W, W, W], base: 0x1B008000, fields: &[Rd, Rn, Rm, Ra] },  // msub Wd, Wn, Wm, Wa
    Form { mnemonic: "msub", ops: &[X, X, X, X], base: 0x9B008000, fields: &[Rd, Rn, Rm, Ra] },  // msub Xd, Xn, Xm, Xa
    Form { mnemonic: "msubpt", ops: &[X, X, X, X], base: 0x9B608000, fields: &[Rd, Rn, Rm, Ra] },  // msubpt Xd, Xn, Xm, Xa
    Form { mnemonic: "mul", ops: &[W, W, W], base: 0x1B007C00, fields: &[Rd, Rn, Rm] },  // mul Wd, Wn, Wm
    Form { mnemonic: "mul", ops: &[X, X, X], base: 0x9B007C00, fields: &[Rd, Rn, Rm] },  // mul Xd, Xn, Xm
    Form { mnemonic: "nop", ops: &[], base: 0xD503201F, fields: &[] },  // nop
    Form { mnemonic: "orn", ops: &[W, W, W], base: 0x2A200000, fields: &[Rd, Rn, Rm] },  // orn Wd, Wn, Wm, {sop #n}
    Form { mnemonic: "orn", ops: &[X, X, X], base: 0xAA200000, fields: &[Rd, Rn, Rm] },  // orn Xd, Xn, Xm, {sop #n}
    Form { mnemonic: "orr", ops: &[W, W, W], base: 0x2A000000, fields: &[Rd, Rn, Rm] },  // orr Wd, Wn, Wm, {sop #n}
    Form { mnemonic: "orr", ops: &[X, X, X], base: 0xAA000000, fields: &[Rd, Rn, Rm] },  // orr Xd, Xn, Xm, {sop #n}
    Form { mnemonic: "orr", ops: &[W, W, Imm], base: 0x32000000, fields: &[Rd, Rn, LogicalImm { op: 2, is64: false }] },  // orr Wd|WSP, Wn, #log_imm
    Form { mnemonic: "orr", ops: &[X, X, Imm], base: 0xB2000000, fields: &[Rd, Rn, LogicalImm { op: 2, is64: true }] },  // orr Xd|SP, Xn, #log_imm
    Form { mnemonic: "pacda", ops: &[X, X], base: 0xDAC10800, fields: &[Rd, Rn] },  // pacda Xd, Xn|SP
    Form { mnemonic: "pacdb", ops: &[X, X], base: 0xDAC10C00, fields: &[Rd, Rn] },  // pacdb Xd, Xn|SP
    Form { mnemonic: "pacdza", ops: &[X], base: 0xDAC12BE0, fields: &[Rd] },  // pacdza Xd
    Form { mnemonic: "pacdzb", ops: &[X], base: 0xDAC12FE0, fields: &[Rd] },  // pacdzb Xd
    Form { mnemonic: "pacga", ops: &[X, X, X], base: 0x9AC03000, fields: &[Rd, Rn, Rm] },  // pacga Xd, Xn, Xm|SP
    Form { mnemonic: "pacia", ops: &[X, X], base: 0xDAC10000, fields: &[Rd, Rn] },  // pacia Xd, Xn|SP
    Form { mnemonic: "pacia1716", ops: &[], base: 0xD503211F, fields: &[] },  // pacia1716
    Form { mnemonic: "paciasp", ops: &[], base: 0xD503233F, fields: &[] },  // paciasp
    Form { mnemonic: "paciaz", ops: &[], base: 0xD503231F, fields: &[] },  // paciaz
    Form { mnemonic: "pacib", ops: &[X, X], base: 0xDAC10400, fields: &[Rd, Rn] },  // pacib Xd, Xn|SP
    Form { mnemonic: "pacib1716", ops: &[], base: 0xD503215F, fields: &[] },  // pacib1716
    Form { mnemonic: "pacibsp", ops: &[], base: 0xD503237F, fields: &[] },  // pacibsp
    Form { mnemonic: "pacibz", ops: &[], base: 0xD503235F, fields: &[] },  // pacibz
    Form { mnemonic: "paciza", ops: &[X], base: 0xDAC123E0, fields: &[Rd] },  // paciza Xd
    Form { mnemonic: "pacizb", ops: &[X], base: 0xDAC127E0, fields: &[Rd] },  // pacizb Xd
    Form { mnemonic: "pssbb", ops: &[], base: 0xD503349F, fields: &[] },  // pssbb
    Form { mnemonic: "rbit", ops: &[W, W], base: 0x5AC00000, fields: &[Rd, Rn] },  // rbit Wd, Wn
    Form { mnemonic: "rbit", ops: &[X, X], base: 0xDAC00000, fields: &[Rd, Rn] },  // rbit Xd, Xn
    Form { mnemonic: "retaa", ops: &[], base: 0xD65F0BFF, fields: &[] },  // retaa
    Form { mnemonic: "retab", ops: &[], base: 0xD65F0FFF, fields: &[] },  // retab
    Form { mnemonic: "rev", ops: &[W, W], base: 0x5AC00800, fields: &[Rd, Rn] },  // rev Wd, Wn
    Form { mnemonic: "rev", ops: &[X, X], base: 0xDAC00C00, fields: &[Rd, Rn] },  // rev|rev64 Xd, Xn
    Form { mnemonic: "rev16", ops: &[W, W], base: 0x5AC00400, fields: &[Rd, Rn] },  // rev16 Wd, Wn
    Form { mnemonic: "rev16", ops: &[X, X], base: 0xDAC00400, fields: &[Rd, Rn] },  // rev16 Xd, Xn
    Form { mnemonic: "rev32", ops: &[X, X], base: 0xDAC00800, fields: &[Rd, Rn] },  // rev32 Xd, Xn
    Form { mnemonic: "rev64", ops: &[X, X], base: 0xDAC00C00, fields: &[Rd, Rn] },  // rev|rev64 Xd, Xn
    Form { mnemonic: "ror", ops: &[W, W, W], base: 0x1AC02C00, fields: &[Rd, Rn, Rm] },  // ror|rorv Wd, Wn, Wm
    Form { mnemonic: "ror", ops: &[X, X, X], base: 0x9AC02C00, fields: &[Rd, Rn, Rm] },  // ror|rorv Xd, Xn, Xm
    Form { mnemonic: "rorv", ops: &[W, W, W], base: 0x1AC02C00, fields: &[Rd, Rn, Rm] },  // ror|rorv Wd, Wn, Wm
    Form { mnemonic: "rorv", ops: &[X, X, X], base: 0x9AC02C00, fields: &[Rd, Rn, Rm] },  // ror|rorv Xd, Xn, Xm
    Form { mnemonic: "sb", ops: &[], base: 0xD50330FF, fields: &[] },  // sb
    Form { mnemonic: "sbc", ops: &[W, W, W], base: 0x5A000000, fields: &[Rd, Rn, Rm] },  // sbc Wd, Wn, Wm
    Form { mnemonic: "sbc", ops: &[X, X, X], base: 0xDA000000, fields: &[Rd, Rn, Rm] },  // sbc Xd, Xn, Xm
    Form { mnemonic: "sbcs", ops: &[W, W, W], base: 0x7A000000, fields: &[Rd, Rn, Rm] },  // sbcs Wd, Wn, Wm
    Form { mnemonic: "sbcs", ops: &[X, X, X], base: 0xFA000000, fields: &[Rd, Rn, Rm] },  // sbcs Xd, Xn, Xm
    Form { mnemonic: "sdiv", ops: &[W, W, W], base: 0x1AC00C00, fields: &[Rd, Rn, Rm] },  // sdiv Wd, Wn, Wm
    Form { mnemonic: "sdiv", ops: &[X, X, X], base: 0x9AC00C00, fields: &[Rd, Rn, Rm] },  // sdiv Xd, Xn, Xm
    Form { mnemonic: "sev", ops: &[], base: 0xD503209F, fields: &[] },  // sev
    Form { mnemonic: "sevl", ops: &[], base: 0xD50320BF, fields: &[] },  // sevl
    Form { mnemonic: "smaddl", ops: &[X, W, W, X], base: 0x9B200000, fields: &[Rd, Rn, Rm, Ra] },  // smaddl Xd, Wn, Wm, Xa
    Form { mnemonic: "smax", ops: &[W, W, W], base: 0x1AC06000, fields: &[Rd, Rn, Rm] },  // smax Wd, Wn, Wm
    Form { mnemonic: "smax", ops: &[X, X, X], base: 0x9AC06000, fields: &[Rd, Rn, Rm] },  // smax Xd, Xn, Xm
    Form { mnemonic: "smc", ops: &[Imm], base: 0xD4000003, fields: &[UImm { op: 0, shift: 5, width: 16 }] },  // smc #immZ
    Form { mnemonic: "smin", ops: &[W, W, W], base: 0x1AC06800, fields: &[Rd, Rn, Rm] },  // smin Wd, Wn, Wm
    Form { mnemonic: "smin", ops: &[X, X, X], base: 0x9AC06800, fields: &[Rd, Rn, Rm] },  // smin Xd, Xn, Xm
    Form { mnemonic: "smnegl", ops: &[X, W, W], base: 0x9B20FC00, fields: &[Rd, Rn, Rm] },  // smnegl Xd, Wn, Wm
    Form { mnemonic: "smsubl", ops: &[X, W, W, X], base: 0x9B208000, fields: &[Rd, Rn, Rm, Ra] },  // smsubl Xd, Wn, Wm, Xa
    Form { mnemonic: "smulh", ops: &[X, X, X], base: 0x9B407C00, fields: &[Rd, Rn, Rm] },  // smulh Xd, Xn, Xm
    Form { mnemonic: "smull", ops: &[X, W, W], base: 0x9B207C00, fields: &[Rd, Rn, Rm] },  // smull Xd, Wn, Wm
    Form { mnemonic: "ssbb", ops: &[], base: 0xD503309F, fields: &[] },  // ssbb
    Form { mnemonic: "sub", ops: &[W, W, W], base: 0x4B000000, fields: &[Rd, Rn, Rm] },  // sub Wd, Wn, Wm, {lsl|lsr|asr #n}
    Form { mnemonic: "sub", ops: &[X, X, X], base: 0xCB000000, fields: &[Rd, Rn, Rm] },  // sub Xd, Xn, Xm, {lsl|lsr|asr #n}
    Form { mnemonic: "sub", ops: &[W, W, Imm], base: 0x51000000, fields: &[Rd, Rn, UImm { op: 2, shift: 10, width: 12 }] },  // sub Wd|WSP, Wn|WSP, #immZ, {lsl #n=0|12}
    Form { mnemonic: "sub", ops: &[X, X, Imm], base: 0xD1000000, fields: &[Rd, Rn, UImm { op: 2, shift: 10, width: 12 }] },  // sub Xd|SP, Xn|SP, #immZ, {lsl #n=0|12}
    Form { mnemonic: "subp", ops: &[X, X, X], base: 0x9AC00000, fields: &[Rd, Rn, Rm] },  // subp Xd, Xn|SP, Xm|SP
    Form { mnemonic: "subps", ops: &[X, X, X], base: 0xBAC00000, fields: &[Rd, Rn, Rm] },  // subps Xd, Xn|SP, Xm|SP
    Form { mnemonic: "subpt", ops: &[X, X, X], base: 0xDA002000, fields: &[Rd, Rn, Rm] },  // subpt Xd|SP, Xn|SP, Xm, {lsl #n}
    Form { mnemonic: "subs", ops: &[W, W, W], base: 0x6B000000, fields: &[Rd, Rn, Rm] },  // subs Wd, Wn, Wm, {lsl|lsr|asr #n}
    Form { mnemonic: "subs", ops: &[X, X, X], base: 0xEB000000, fields: &[Rd, Rn, Rm] },  // subs Xd, Xn, Xm, {lsl|lsr|asr #n}
    Form { mnemonic: "subs", ops: &[W, W, Imm], base: 0x71000000, fields: &[Rd, Rn, UImm { op: 2, shift: 10, width: 12 }] },  // subs Wd|WSP, Wn|WSP, #immZ, {lsl #n=0|12}
    Form { mnemonic: "subs", ops: &[X, X, Imm], base: 0xF1000000, fields: &[Rd, Rn, UImm { op: 2, shift: 10, width: 12 }] },  // subs Xd|SP, Xn|SP, #immZ, {lsl #n=0|12}
    Form { mnemonic: "svc", ops: &[Imm], base: 0xD4000001, fields: &[UImm { op: 0, shift: 5, width: 16 }] },  // svc #immZ
    Form { mnemonic: "sxtb", ops: &[W, W], base: 0x13001C00, fields: &[Rd, Rn] },  // sxtb Wd, Wn
    Form { mnemonic: "sxtb", ops: &[X, W], base: 0x93401C00, fields: &[Rd, Rn] },  // sxtb Xd, Wn
    Form { mnemonic: "sxth", ops: &[W, W], base: 0x13003C00, fields: &[Rd, Rn] },  // sxth Wd, Wn
    Form { mnemonic: "sxth", ops: &[X, W], base: 0x93403C00, fields: &[Rd, Rn] },  // sxth Xd, Wn
    Form { mnemonic: "sxtw", ops: &[X, W], base: 0x93407C00, fields: &[Rd, Rn] },  // sxtw Xd, Wn
    Form { mnemonic: "tcancel", ops: &[Imm], base: 0xD4600000, fields: &[UImm { op: 0, shift: 5, width: 16 }] },  // tcancel #imm
    Form { mnemonic: "tcommit", ops: &[], base: 0xD503307F, fields: &[] },  // tcommit
    Form { mnemonic: "ttest", ops: &[X], base: 0xD5233160, fields: &[Rd] },  // ttest Xd
    Form { mnemonic: "udf", ops: &[Imm], base: 0x00000000, fields: &[UImm { op: 0, shift: 0, width: 16 }] },  // udf #imm
    Form { mnemonic: "udiv", ops: &[W, W, W], base: 0x1AC00800, fields: &[Rd, Rn, Rm] },  // udiv Wd, Wn, Wm
    Form { mnemonic: "udiv", ops: &[X, X, X], base: 0x9AC00800, fields: &[Rd, Rn, Rm] },  // udiv Xd, Xn, Xm
    Form { mnemonic: "umaddl", ops: &[X, W, W, X], base: 0x9BA00000, fields: &[Rd, Rn, Rm, Ra] },  // umaddl Xd, Wn, Wm, Xa
    Form { mnemonic: "umax", ops: &[W, W, W], base: 0x1AC06400, fields: &[Rd, Rn, Rm] },  // umax Wd, Wn, Wm
    Form { mnemonic: "umax", ops: &[X, X, X], base: 0x9AC06400, fields: &[Rd, Rn, Rm] },  // umax Xd, Xn, Xm
    Form { mnemonic: "umax", ops: &[W, W, Imm], base: 0x11C40000, fields: &[Rd, Rn, UImm { op: 2, shift: 10, width: 8 }] },  // umax Wd, Wn, #immZ
    Form { mnemonic: "umax", ops: &[X, X, Imm], base: 0x91C40000, fields: &[Rd, Rn, UImm { op: 2, shift: 10, width: 8 }] },  // umax Xd, Xn, #immZ
    Form { mnemonic: "umin", ops: &[W, W, W], base: 0x1AC06C00, fields: &[Rd, Rn, Rm] },  // umin Wd, Wn, Wm
    Form { mnemonic: "umin", ops: &[X, X, X], base: 0x9AC06C00, fields: &[Rd, Rn, Rm] },  // umin Xd, Xn, Xm
    Form { mnemonic: "umin", ops: &[W, W, Imm], base: 0x11CC0000, fields: &[Rd, Rn, UImm { op: 2, shift: 10, width: 8 }] },  // umin Wd, Wn, #immZ
    Form { mnemonic: "umin", ops: &[X, X, Imm], base: 0x91CC0000, fields: &[Rd, Rn, UImm { op: 2, shift: 10, width: 8 }] },  // umin Xd, Xn, #immZ
    Form { mnemonic: "umnegl", ops: &[X, W, W], base: 0x9BA0FC00, fields: &[Rd, Rn, Rm] },  // umnegl Xd, Wn, Wm
    Form { mnemonic: "umsubl", ops: &[X, W, W, X], base: 0x9BA08000, fields: &[Rd, Rn, Rm, Ra] },  // umsubl Xd, Wn, Wm, Xa
    Form { mnemonic: "umulh", ops: &[X, X, X], base: 0x9BC07C00, fields: &[Rd, Rn, Rm] },  // umulh Xd, Xn, Xm
    Form { mnemonic: "umull", ops: &[X, W, W], base: 0x9BA07C00, fields: &[Rd, Rn, Rm] },  // umull Xd, Wn, Wm
    Form { mnemonic: "uxtb", ops: &[W, W], base: 0x53001C00, fields: &[Rd, Rn] },  // uxtb Wd, Wn
    Form { mnemonic: "uxth", ops: &[W, W], base: 0x53003C00, fields: &[Rd, Rn] },  // uxth Wd, Wn
    Form { mnemonic: "wfe", ops: &[], base: 0xD503205F, fields: &[] },  // wfe
    Form { mnemonic: "wfi", ops: &[], base: 0xD503207F, fields: &[] },  // wfi
    Form { mnemonic: "xaflag", ops: &[], base: 0xD500403F, fields: &[] },  // xaflag
    Form { mnemonic: "xpacd", ops: &[X], base: 0xDAC147E0, fields: &[Rd] },  // xpacd Xd
    Form { mnemonic: "xpaci", ops: &[X], base: 0xDAC143E0, fields: &[Rd] },  // xpaci Xd
    Form { mnemonic: "yield", ops: &[], base: 0xD503203F, fields: &[] },  // yield
];
