// mach/vm_statistics.h -- the Mach VM allocation flags and the user
// memory tag namespace. macOS only.
//
// Values follow the macOS SDK header of the same name. The virtual
// memory statistics structures (vm_statistics, vm_statistics64,
// vm_extmod_statistics) and the ledger tags are not declared: they are
// only reachable through host_statistics64 / ledger calls, which badc
// does not bind.

#pragma once

#ifdef __APPLE__
// Flags for the `flags` argument of mach_vm_map / mach_vm_allocate, and
// for mmap's fd argument once combined with a tag through VM_MAKE_TAG.
#define VM_FLAGS_FIXED                  0x00000000
#define VM_FLAGS_ANYWHERE               0x00000001
#define VM_FLAGS_PURGABLE               0x00000002
#define VM_FLAGS_4GB_CHUNK              0x00000004
#define VM_FLAGS_RANDOM_ADDR            0x00000008
#define VM_FLAGS_NO_CACHE               0x00000010
#define VM_FLAGS_RESILIENT_CODESIGN     0x00000020
#define VM_FLAGS_RESILIENT_MEDIA        0x00000040
#define VM_FLAGS_PERMANENT              0x00000080
#define VM_FLAGS_TPRO                   0x00001000
#define VM_FLAGS_MTE                    0x00002000
#define VM_FLAGS_OVERWRITE              0x00004000
#define VM_FLAGS_SUPERPAGE_MASK         0x00070000
#define VM_FLAGS_RETURN_DATA_ADDR       0x00100000
#define VM_FLAGS_GUARD_OBJECT_OPTOUT    0x00400000
#define VM_FLAGS_RETURN_4K_DATA_ADDR    0x00800000
#define VM_FLAGS_ALIAS_MASK             0xFF000000

#define VM_FLAGS_SUPERPAGE_SHIFT 16
#define SUPERPAGE_NONE                  0
#define SUPERPAGE_SIZE_ANY              1
#define SUPERPAGE_SIZE_2MB              2
#define VM_FLAGS_SUPERPAGE_NONE     (SUPERPAGE_NONE     << VM_FLAGS_SUPERPAGE_SHIFT)
#define VM_FLAGS_SUPERPAGE_SIZE_ANY (SUPERPAGE_SIZE_ANY << VM_FLAGS_SUPERPAGE_SHIFT)
#define VM_FLAGS_SUPERPAGE_SIZE_2MB (SUPERPAGE_SIZE_2MB << VM_FLAGS_SUPERPAGE_SHIFT)

// vm_reallocate options.
#define VM_REALLOCATE_DEALLOCATE_SOURCE 0x0
#define VM_REALLOCATE_ZERO_FILL_SOURCE  0x1

// A tag occupies the top 8 bits of the flags word.
#define VM_MAKE_TAG(tag) ((tag) << 24)

// User memory tags. Tags 240-255 are reserved for applications; the rest
// name a system allocator or framework and are assigned by the platform.
#define VM_MEMORY_MALLOC 1
#define VM_MEMORY_MALLOC_SMALL 2
#define VM_MEMORY_MALLOC_LARGE 3
#define VM_MEMORY_MALLOC_HUGE 4
#define VM_MEMORY_SBRK 5
#define VM_MEMORY_REALLOC 6
#define VM_MEMORY_MALLOC_TINY 7
#define VM_MEMORY_MALLOC_LARGE_REUSABLE 8
#define VM_MEMORY_MALLOC_LARGE_REUSED 9
#define VM_MEMORY_ANALYSIS_TOOL 10
#define VM_MEMORY_MALLOC_NANO 11
#define VM_MEMORY_MALLOC_MEDIUM 12
#define VM_MEMORY_MALLOC_PROB_GUARD 13
#define VM_MEMORY_MACH_MSG 20
#define VM_MEMORY_IOKIT 21
#define VM_MEMORY_VM_RECLAIM 22
#define VM_MEMORY_STACK 30
#define VM_MEMORY_GUARD 31
#define VM_MEMORY_SHARED_PMAP 32
#define VM_MEMORY_DYLIB 33
#define VM_MEMORY_OBJC_DISPATCHERS 34
#define VM_MEMORY_UNSHARED_PMAP 35
#define VM_MEMORY_LIBCHANNEL 36
#define VM_MEMORY_APPKIT 40
#define VM_MEMORY_FOUNDATION 41
#define VM_MEMORY_COREGRAPHICS 42
#define VM_MEMORY_CORESERVICES 43
#define VM_MEMORY_CARBON VM_MEMORY_CORESERVICES
#define VM_MEMORY_JAVA 44
#define VM_MEMORY_COREDATA 45
#define VM_MEMORY_COREDATA_OBJECTIDS 46
#define VM_MEMORY_ATS 50
#define VM_MEMORY_LAYERKIT 51
#define VM_MEMORY_CGIMAGE 52
#define VM_MEMORY_TCMALLOC 53
#define VM_MEMORY_COREGRAPHICS_DATA 54
#define VM_MEMORY_COREGRAPHICS_SHARED 55
#define VM_MEMORY_COREGRAPHICS_FRAMEBUFFERS 56
#define VM_MEMORY_COREGRAPHICS_BACKINGSTORES 57
#define VM_MEMORY_COREGRAPHICS_XALLOC 58
#define VM_MEMORY_COREGRAPHICS_MISC VM_MEMORY_COREGRAPHICS
#define VM_MEMORY_DYLD 60
#define VM_MEMORY_DYLD_MALLOC 61
#define VM_MEMORY_SQLITE 62
#define VM_MEMORY_JAVASCRIPT_CORE 63
#define VM_MEMORY_WEBASSEMBLY VM_MEMORY_JAVASCRIPT_CORE
#define VM_MEMORY_JAVASCRIPT_JIT_EXECUTABLE_ALLOCATOR 64
#define VM_MEMORY_JAVASCRIPT_JIT_REGISTER_FILE 65
#define VM_MEMORY_GLSL 66
#define VM_MEMORY_OPENCL 67
#define VM_MEMORY_COREIMAGE 68
#define VM_MEMORY_WEBCORE_PURGEABLE_BUFFERS 69
#define VM_MEMORY_IMAGEIO 70
#define VM_MEMORY_COREPROFILE 71
#define VM_MEMORY_ASSETSD 72
#define VM_MEMORY_OS_ALLOC_ONCE 73
#define VM_MEMORY_LIBDISPATCH 74
#define VM_MEMORY_ACCELERATE 75
#define VM_MEMORY_COREUI 76
#define VM_MEMORY_COREUIFILE 77
#define VM_MEMORY_GENEALOGY 78
#define VM_MEMORY_RAWCAMERA 79
#define VM_MEMORY_CORPSEINFO 80
#define VM_MEMORY_ASL 81
#define VM_MEMORY_SWIFT_RUNTIME 82
#define VM_MEMORY_SWIFT_METADATA 83
#define VM_MEMORY_DHMM 84
#define VM_MEMORY_DFR 85
#define VM_MEMORY_SCENEKIT 86
#define VM_MEMORY_SKYWALK 87
#define VM_MEMORY_IOSURFACE 88
#define VM_MEMORY_LIBNETWORK 89
#define VM_MEMORY_AUDIO 90
#define VM_MEMORY_VIDEOBITSTREAM 91
#define VM_MEMORY_CM_XPC 92
#define VM_MEMORY_CM_RPC 93
#define VM_MEMORY_CM_MEMORYPOOL 94
#define VM_MEMORY_CM_READCACHE 95
#define VM_MEMORY_CM_CRABS 96
#define VM_MEMORY_QUICKLOOK_THUMBNAILS 97
#define VM_MEMORY_ACCOUNTS 98
#define VM_MEMORY_SANITIZER 99
#define VM_MEMORY_IOACCELERATOR 100
#define VM_MEMORY_CM_REGWARP 101
#define VM_MEMORY_EAR_DECODER 102
#define VM_MEMORY_COREUI_CACHED_IMAGE_DATA 103
#define VM_MEMORY_COLORSYNC 104
#define VM_MEMORY_BTINFO 105
#define VM_MEMORY_CM_HLS 106
#define VM_MEMORY_COMPOSITOR_SERVICES 107
#define VM_MEMORY_ROSETTA 230
#define VM_MEMORY_ROSETTA_THREAD_CONTEXT 231
#define VM_MEMORY_ROSETTA_INDIRECT_BRANCH_MAP 232
#define VM_MEMORY_ROSETTA_RETURN_STACK 233
#define VM_MEMORY_ROSETTA_EXECUTABLE_HEAP 234
#define VM_MEMORY_ROSETTA_USER_LDT 235
#define VM_MEMORY_ROSETTA_ARENA 236
#define VM_MEMORY_ROSETTA_10 239
#define VM_MEMORY_APPLICATION_SPECIFIC_1 240
#define VM_MEMORY_APPLICATION_SPECIFIC_2 241
#define VM_MEMORY_APPLICATION_SPECIFIC_3 242
#define VM_MEMORY_APPLICATION_SPECIFIC_4 243
#define VM_MEMORY_APPLICATION_SPECIFIC_5 244
#define VM_MEMORY_APPLICATION_SPECIFIC_6 245
#define VM_MEMORY_APPLICATION_SPECIFIC_7 246
#define VM_MEMORY_APPLICATION_SPECIFIC_8 247
#define VM_MEMORY_APPLICATION_SPECIFIC_9 248
#define VM_MEMORY_APPLICATION_SPECIFIC_10 249
#define VM_MEMORY_APPLICATION_SPECIFIC_11 250
#define VM_MEMORY_APPLICATION_SPECIFIC_12 251
#define VM_MEMORY_APPLICATION_SPECIFIC_13 252
#define VM_MEMORY_APPLICATION_SPECIFIC_14 253
#define VM_MEMORY_APPLICATION_SPECIFIC_15 254
#define VM_MEMORY_APPLICATION_SPECIFIC_16 255
#define VM_MEMORY_COUNT 256
#endif
