// @generated by tools/gen_isa.py from an external instruction-set
// database. Do not edit by hand; re-run the generator to update.
//
// The x86-64 GP / system encoder catalogue interpreted by
// `super::table::encode`.

use super::table::{Form, ImmC, Map, OpPat::*, RegField::*, RexW::*, W};
use Mnem::*;

/// Every mnemonic the catalogue encodes. Generated; the native emitter
/// passes these instead of strings, and the inline-asm parser maps a
/// token to one via `Mnem::from_name`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) enum Mnem {
    Adc,
    Add,
    And,
    Bsf,
    Bsr,
    Bswap,
    Bt,
    Btc,
    Btr,
    Bts,
    Cdq,
    Cdqe,
    Clc,
    Cld,
    Clflush,
    Cli,
    Cltd,
    Cltq,
    Clts,
    Cmc,
    Cmova,
    Cmovae,
    Cmovb,
    Cmovbe,
    Cmovc,
    Cmove,
    Cmovg,
    Cmovge,
    Cmovl,
    Cmovle,
    Cmovna,
    Cmovnae,
    Cmovnb,
    Cmovnbe,
    Cmovnc,
    Cmovne,
    Cmovng,
    Cmovnge,
    Cmovnl,
    Cmovnle,
    Cmovno,
    Cmovnp,
    Cmovns,
    Cmovnz,
    Cmovo,
    Cmovp,
    Cmovpe,
    Cmovpo,
    Cmovs,
    Cmovz,
    Cmp,
    Cmpxchg,
    Cpuid,
    Cqo,
    Cqto,
    Cwde,
    Cwtl,
    Dec,
    Div,
    Fxrstor,
    Fxrstor64,
    Fxsave,
    Fxsave64,
    Hlt,
    Idiv,
    Imul,
    In,
    Inc,
    Int,
    Int3,
    Invd,
    Iretq,
    Lahf,
    Lea,
    Leave,
    Lfence,
    Lgdt,
    Lidt,
    Mfence,
    Monitor,
    Mov,
    Movnti,
    Movsx,
    Movsxd,
    Movzx,
    Mul,
    Mwait,
    Neg,
    Nop,
    Not,
    Or,
    Out,
    Pop,
    Prefetchnta,
    Prefetcht0,
    Prefetcht1,
    Prefetcht2,
    Prefetchw,
    Push,
    Rcl,
    Rcr,
    Rdmsr,
    Rdpkru,
    Rdpmc,
    Rdrand,
    Rdseed,
    Rdtsc,
    Rdtscp,
    Ret,
    Rol,
    Ror,
    Sahf,
    Sal,
    Sar,
    Sbb,
    Serialize,
    Seta,
    Setae,
    Setb,
    Setbe,
    Setc,
    Sete,
    Setg,
    Setge,
    Setl,
    Setle,
    Setna,
    Setnae,
    Setnb,
    Setnbe,
    Setnc,
    Setne,
    Setng,
    Setnge,
    Setnl,
    Setnle,
    Setno,
    Setnp,
    Setns,
    Setnz,
    Seto,
    Setp,
    Setpe,
    Setpo,
    Sets,
    Setz,
    Sfence,
    Sgdt,
    Shl,
    Shr,
    Sidt,
    Stc,
    Std,
    Sti,
    Sub,
    Swapgs,
    Syscall,
    Sysenter,
    Sysexit,
    Sysret,
    Test,
    Ud2,
    Wbinvd,
    Wrmsr,
    Xadd,
    Xchg,
    Xgetbv,
    Xor,
    Xsetbv,
}

#[rustfmt::skip]
pub(crate) static FORMS: &[Form] = &[
    Form { mnem: Adc, mnemonic: "adc", ops: &[Fixed(0, W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x14], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 1 },  // adc al imm8
    Form { mnem: Adc, mnemonic: "adc", ops: &[Fixed(0, W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x15], plus_r: false, rexw: ByWidth, reg: NoReg, rm: 255, imm: Some(ImmC::Iv), imm_op: 1 },  // adc axv immv
    Form { mnem: Adc, mnemonic: "adc", ops: &[Rm(W::B), Reg(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x10], plus_r: false, rexw: W0, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // adc r8/m8 r8
    Form { mnem: Adc, mnemonic: "adc", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x11], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // adc rv/mv rv
    Form { mnem: Adc, mnemonic: "adc", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x80], plus_r: false, rexw: W0, reg: Ext(2), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // adc r8/m8 imm8
    Form { mnem: Adc, mnemonic: "adc", ops: &[Rm(W::V), Imm(ImmC::Imms8)], pp: &[], map: Map::Legacy, opcode: &[0x83], plus_r: false, rexw: ByWidth, reg: Ext(2), rm: 0, imm: Some(ImmC::Imms8), imm_op: 1 },  // adc rv/mv imms8
    Form { mnem: Adc, mnemonic: "adc", ops: &[Rm(W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x81], plus_r: false, rexw: ByWidth, reg: Ext(2), rm: 0, imm: Some(ImmC::Iv), imm_op: 1 },  // adc rv/mv immv
    Form { mnem: Adc, mnemonic: "adc", ops: &[Reg(W::B), Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x12], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // adc r8 r8/m8
    Form { mnem: Adc, mnemonic: "adc", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x13], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // adc rv rv/mv
    Form { mnem: Add, mnemonic: "add", ops: &[Fixed(0, W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x04], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 1 },  // add al imm8
    Form { mnem: Add, mnemonic: "add", ops: &[Fixed(0, W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x05], plus_r: false, rexw: ByWidth, reg: NoReg, rm: 255, imm: Some(ImmC::Iv), imm_op: 1 },  // add axv immv
    Form { mnem: Add, mnemonic: "add", ops: &[Rm(W::B), Reg(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x00], plus_r: false, rexw: W0, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // add r8/m8 r8
    Form { mnem: Add, mnemonic: "add", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x01], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // add rv/mv rv
    Form { mnem: Add, mnemonic: "add", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x80], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // add r8/m8 imm8
    Form { mnem: Add, mnemonic: "add", ops: &[Rm(W::V), Imm(ImmC::Imms8)], pp: &[], map: Map::Legacy, opcode: &[0x83], plus_r: false, rexw: ByWidth, reg: Ext(0), rm: 0, imm: Some(ImmC::Imms8), imm_op: 1 },  // add rv/mv imms8
    Form { mnem: Add, mnemonic: "add", ops: &[Rm(W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x81], plus_r: false, rexw: ByWidth, reg: Ext(0), rm: 0, imm: Some(ImmC::Iv), imm_op: 1 },  // add rv/mv immv
    Form { mnem: Add, mnemonic: "add", ops: &[Reg(W::B), Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x02], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // add r8 r8/m8
    Form { mnem: Add, mnemonic: "add", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x03], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // add rv rv/mv
    Form { mnem: And, mnemonic: "and", ops: &[Fixed(0, W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x24], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 1 },  // and al imm8
    Form { mnem: And, mnemonic: "and", ops: &[Fixed(0, W::Wd), Imm(ImmC::Iw)], pp: &[], map: Map::Legacy, opcode: &[0x25], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Iw), imm_op: 1 },  // and ax imm16
    Form { mnem: And, mnemonic: "and", ops: &[Fixed(0, W::L), Imm(ImmC::Id)], pp: &[], map: Map::Legacy, opcode: &[0x25], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Id), imm_op: 1 },  // and eax imm32
    Form { mnem: And, mnemonic: "and", ops: &[Fixed(0, W::Q), Imm(ImmC::Id)], pp: &[], map: Map::Legacy, opcode: &[0x25], plus_r: false, rexw: ByWidth, reg: NoReg, rm: 255, imm: Some(ImmC::Id), imm_op: 1 },  // and rax immu32
    Form { mnem: And, mnemonic: "and", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x80], plus_r: false, rexw: W0, reg: Ext(4), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // and r8/m8 imm8
    Form { mnem: And, mnemonic: "and", ops: &[Rm(W::Wd), Imm(ImmC::Iw)], pp: &[], map: Map::Legacy, opcode: &[0x81], plus_r: false, rexw: W0, reg: Ext(4), rm: 0, imm: Some(ImmC::Iw), imm_op: 1 },  // and r16/m16 imm16
    Form { mnem: And, mnemonic: "and", ops: &[Rm(W::L), Imm(ImmC::Id)], pp: &[], map: Map::Legacy, opcode: &[0x81], plus_r: false, rexw: W0, reg: Ext(4), rm: 0, imm: Some(ImmC::Id), imm_op: 1 },  // and r32/m32 imm32
    Form { mnem: And, mnemonic: "and", ops: &[Reg(W::Q), Imm(ImmC::Id)], pp: &[], map: Map::Legacy, opcode: &[0x81], plus_r: false, rexw: ByWidth, reg: Ext(4), rm: 0, imm: Some(ImmC::Id), imm_op: 1 },  // and r64 immu32
    Form { mnem: And, mnemonic: "and", ops: &[Rm(W::Q), Imm(ImmC::Id)], pp: &[], map: Map::Legacy, opcode: &[0x81], plus_r: false, rexw: W1, reg: Ext(4), rm: 0, imm: Some(ImmC::Id), imm_op: 1 },  // and r64/m64 imms32
    Form { mnem: And, mnemonic: "and", ops: &[Rm(W::V), Imm(ImmC::Imms8)], pp: &[], map: Map::Legacy, opcode: &[0x83], plus_r: false, rexw: ByWidth, reg: Ext(4), rm: 0, imm: Some(ImmC::Imms8), imm_op: 1 },  // and rv/mv imms8
    Form { mnem: And, mnemonic: "and", ops: &[Rm(W::B), Reg(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x20], plus_r: false, rexw: W0, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // and r8/m8 r8
    Form { mnem: And, mnemonic: "and", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x21], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // and rv/mv rv
    Form { mnem: And, mnemonic: "and", ops: &[Reg(W::B), Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x22], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // and r8 r8/m8
    Form { mnem: And, mnemonic: "and", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x23], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // and rv rv/mv
    Form { mnem: Bsf, mnemonic: "bsf", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0xBC], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // bsf rv rv/mv
    Form { mnem: Bsr, mnemonic: "bsr", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0xBD], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // bsr rv rv/mv
    Form { mnem: Bswap, mnemonic: "bswap", ops: &[Reg(W::V)], pp: &[], map: Map::Op0F, opcode: &[0xC8], plus_r: true, rexw: ByWidth, reg: NoReg, rm: 0, imm: None, imm_op: 255 },  // bswap rv
    Form { mnem: Bt, mnemonic: "bt", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Op0F, opcode: &[0xA3], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // bt rv/mv rv
    Form { mnem: Bt, mnemonic: "bt", ops: &[Rm(W::V), Imm(ImmC::Ib)], pp: &[], map: Map::Op0F, opcode: &[0xBA], plus_r: false, rexw: ByWidth, reg: Ext(4), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // bt rv/mv imm8
    Form { mnem: Btc, mnemonic: "btc", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Op0F, opcode: &[0xBB], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // btc rv/mv rv
    Form { mnem: Btc, mnemonic: "btc", ops: &[Rm(W::V), Imm(ImmC::Ib)], pp: &[], map: Map::Op0F, opcode: &[0xBA], plus_r: false, rexw: ByWidth, reg: Ext(7), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // btc rv/mv imm8
    Form { mnem: Btr, mnemonic: "btr", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Op0F, opcode: &[0xB3], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // btr rv/mv rv
    Form { mnem: Btr, mnemonic: "btr", ops: &[Rm(W::V), Imm(ImmC::Ib)], pp: &[], map: Map::Op0F, opcode: &[0xBA], plus_r: false, rexw: ByWidth, reg: Ext(6), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // btr rv/mv imm8
    Form { mnem: Bts, mnemonic: "bts", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Op0F, opcode: &[0xAB], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // bts rv/mv rv
    Form { mnem: Bts, mnemonic: "bts", ops: &[Rm(W::V), Imm(ImmC::Ib)], pp: &[], map: Map::Op0F, opcode: &[0xBA], plus_r: false, rexw: ByWidth, reg: Ext(5), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // bts rv/mv imm8
    Form { mnem: Cdq, mnemonic: "cdq", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0x99], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // cdq edx eax
    Form { mnem: Cdqe, mnemonic: "cdqe", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0x98], plus_r: false, rexw: W1, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // cdqe rax
    Form { mnem: Clc, mnemonic: "clc", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0xF8], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // clc
    Form { mnem: Cld, mnemonic: "cld", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0xFC], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // cld
    Form { mnem: Clflush, mnemonic: "clflush", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0xAE], plus_r: false, rexw: W0, reg: Ext(7), rm: 0, imm: None, imm_op: 255 },  // clflush mem
    Form { mnem: Cli, mnemonic: "cli", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0xFA], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // cli
    Form { mnem: Cltd, mnemonic: "cltd", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0x99], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // cltd edx eax
    Form { mnem: Cltq, mnemonic: "cltq", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0x98], plus_r: false, rexw: W1, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // cltq rax
    Form { mnem: Clts, mnemonic: "clts", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x06], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // clts
    Form { mnem: Cmc, mnemonic: "cmc", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0xF5], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // cmc
    Form { mnem: Cmova, mnemonic: "cmova", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x47], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmova rv rv/mv
    Form { mnem: Cmovae, mnemonic: "cmovae", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x43], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovae rv rv/mv
    Form { mnem: Cmovb, mnemonic: "cmovb", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x42], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovb rv rv/mv
    Form { mnem: Cmovbe, mnemonic: "cmovbe", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x46], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovbe rv rv/mv
    Form { mnem: Cmovc, mnemonic: "cmovc", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x42], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovc rv rv/mv
    Form { mnem: Cmove, mnemonic: "cmove", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x44], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmove rv rv/mv
    Form { mnem: Cmovg, mnemonic: "cmovg", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x4F], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovg rv rv/mv
    Form { mnem: Cmovge, mnemonic: "cmovge", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x4D], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovge rv rv/mv
    Form { mnem: Cmovl, mnemonic: "cmovl", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x4C], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovl rv rv/mv
    Form { mnem: Cmovle, mnemonic: "cmovle", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x4E], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovle rv rv/mv
    Form { mnem: Cmovna, mnemonic: "cmovna", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x46], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovna rv rv/mv
    Form { mnem: Cmovnae, mnemonic: "cmovnae", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x42], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovnae rv rv/mv
    Form { mnem: Cmovnb, mnemonic: "cmovnb", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x43], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovnb rv rv/mv
    Form { mnem: Cmovnbe, mnemonic: "cmovnbe", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x47], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovnbe rv rv/mv
    Form { mnem: Cmovnc, mnemonic: "cmovnc", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x43], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovnc rv rv/mv
    Form { mnem: Cmovne, mnemonic: "cmovne", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x45], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovne rv rv/mv
    Form { mnem: Cmovng, mnemonic: "cmovng", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x4E], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovng rv rv/mv
    Form { mnem: Cmovnge, mnemonic: "cmovnge", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x4C], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovnge rv rv/mv
    Form { mnem: Cmovnl, mnemonic: "cmovnl", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x4D], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovnl rv rv/mv
    Form { mnem: Cmovnle, mnemonic: "cmovnle", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x4F], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovnle rv rv/mv
    Form { mnem: Cmovno, mnemonic: "cmovno", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x41], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovno rv rv/mv
    Form { mnem: Cmovnp, mnemonic: "cmovnp", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x4B], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovnp rv rv/mv
    Form { mnem: Cmovns, mnemonic: "cmovns", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x49], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovns rv rv/mv
    Form { mnem: Cmovnz, mnemonic: "cmovnz", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x45], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovnz rv rv/mv
    Form { mnem: Cmovo, mnemonic: "cmovo", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x40], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovo rv rv/mv
    Form { mnem: Cmovp, mnemonic: "cmovp", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x4A], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovp rv rv/mv
    Form { mnem: Cmovpe, mnemonic: "cmovpe", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x4A], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovpe rv rv/mv
    Form { mnem: Cmovpo, mnemonic: "cmovpo", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x4B], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovpo rv rv/mv
    Form { mnem: Cmovs, mnemonic: "cmovs", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x48], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovs rv rv/mv
    Form { mnem: Cmovz, mnemonic: "cmovz", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x44], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmovz rv rv/mv
    Form { mnem: Cmp, mnemonic: "cmp", ops: &[Rm(W::B), Reg(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x38], plus_r: false, rexw: W0, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // cmp r8/m8 r8
    Form { mnem: Cmp, mnemonic: "cmp", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x39], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // cmp rv/mv rv
    Form { mnem: Cmp, mnemonic: "cmp", ops: &[Reg(W::B), Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x3A], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmp r8 r8/m8
    Form { mnem: Cmp, mnemonic: "cmp", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x3B], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // cmp rv rv/mv
    Form { mnem: Cmp, mnemonic: "cmp", ops: &[Fixed(0, W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x3C], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 1 },  // cmp al imm8
    Form { mnem: Cmp, mnemonic: "cmp", ops: &[Fixed(0, W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x3D], plus_r: false, rexw: ByWidth, reg: NoReg, rm: 255, imm: Some(ImmC::Iv), imm_op: 1 },  // cmp axv immv
    Form { mnem: Cmp, mnemonic: "cmp", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x80], plus_r: false, rexw: W0, reg: Ext(7), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // cmp r8/m8 imm8
    Form { mnem: Cmp, mnemonic: "cmp", ops: &[Rm(W::V), Imm(ImmC::Imms8)], pp: &[], map: Map::Legacy, opcode: &[0x83], plus_r: false, rexw: ByWidth, reg: Ext(7), rm: 0, imm: Some(ImmC::Imms8), imm_op: 1 },  // cmp rv/mv imms8
    Form { mnem: Cmp, mnemonic: "cmp", ops: &[Rm(W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x81], plus_r: false, rexw: ByWidth, reg: Ext(7), rm: 0, imm: Some(ImmC::Iv), imm_op: 1 },  // cmp rv/mv immv
    Form { mnem: Cmpxchg, mnemonic: "cmpxchg", ops: &[Rm(W::B), Reg(W::B)], pp: &[], map: Map::Op0F, opcode: &[0xB0], plus_r: false, rexw: W0, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // cmpxchg r8/m8 r8 al
    Form { mnem: Cmpxchg, mnemonic: "cmpxchg", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Op0F, opcode: &[0xB1], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // cmpxchg rv/mv rv axv
    Form { mnem: Cpuid, mnemonic: "cpuid", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0xA2], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // cpuid eax ebx ecx edx
    Form { mnem: Cqo, mnemonic: "cqo", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0x99], plus_r: false, rexw: W1, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // cqo rdx rax
    Form { mnem: Cqto, mnemonic: "cqto", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0x99], plus_r: false, rexw: W1, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // cqto rdx rax
    Form { mnem: Cwde, mnemonic: "cwde", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0x98], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // cwde eax
    Form { mnem: Cwtl, mnemonic: "cwtl", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0x98], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // cwtl eax
    Form { mnem: Dec, mnemonic: "dec", ops: &[Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0xFE], plus_r: false, rexw: W0, reg: Ext(1), rm: 0, imm: None, imm_op: 255 },  // dec r8/m8
    Form { mnem: Dec, mnemonic: "dec", ops: &[Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0xFF], plus_r: false, rexw: ByWidth, reg: Ext(1), rm: 0, imm: None, imm_op: 255 },  // dec rv/mv
    Form { mnem: Div, mnemonic: "div", ops: &[Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0xF6], plus_r: false, rexw: W0, reg: Ext(6), rm: 0, imm: None, imm_op: 255 },  // div ax r8/m8
    Form { mnem: Div, mnemonic: "div", ops: &[Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0xF7], plus_r: false, rexw: ByWidth, reg: Ext(6), rm: 0, imm: None, imm_op: 255 },  // div dxv axv rv/mv
    Form { mnem: Fxrstor, mnemonic: "fxrstor", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0xAE], plus_r: false, rexw: W0, reg: Ext(1), rm: 0, imm: None, imm_op: 255 },  // fxrstor mem
    Form { mnem: Fxrstor64, mnemonic: "fxrstor64", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0xAE], plus_r: false, rexw: W1, reg: Ext(1), rm: 0, imm: None, imm_op: 255 },  // fxrstor64 mem
    Form { mnem: Fxsave, mnemonic: "fxsave", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0xAE], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // fxsave mem
    Form { mnem: Fxsave64, mnemonic: "fxsave64", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0xAE], plus_r: false, rexw: W1, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // fxsave64 mem
    Form { mnem: Hlt, mnemonic: "hlt", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0xF4], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // hlt
    Form { mnem: Idiv, mnemonic: "idiv", ops: &[Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0xF6], plus_r: false, rexw: W0, reg: Ext(7), rm: 0, imm: None, imm_op: 255 },  // idiv ax r8/m8
    Form { mnem: Idiv, mnemonic: "idiv", ops: &[Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0xF7], plus_r: false, rexw: ByWidth, reg: Ext(7), rm: 0, imm: None, imm_op: 255 },  // idiv dxv axv rv/mv
    Form { mnem: Imul, mnemonic: "imul", ops: &[Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0xF6], plus_r: false, rexw: W0, reg: Ext(5), rm: 0, imm: None, imm_op: 255 },  // imul ax r8/m8
    Form { mnem: Imul, mnemonic: "imul", ops: &[Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0xF7], plus_r: false, rexw: ByWidth, reg: Ext(5), rm: 0, imm: None, imm_op: 255 },  // imul dxv axv rv/mv
    Form { mnem: Imul, mnemonic: "imul", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0xAF], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // imul rv rv/mv
    Form { mnem: Imul, mnemonic: "imul", ops: &[Reg(W::V), Rm(W::V), Imm(ImmC::Imms8)], pp: &[], map: Map::Legacy, opcode: &[0x6B], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: Some(ImmC::Imms8), imm_op: 2 },  // imul rv rv/mv imms8
    Form { mnem: Imul, mnemonic: "imul", ops: &[Reg(W::V), Rm(W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x69], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: Some(ImmC::Iv), imm_op: 2 },  // imul rv rv/mv immv
    Form { mnem: In, mnemonic: "in", ops: &[Fixed(0, W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xE4], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 1 },  // in al imm8
    Form { mnem: In, mnemonic: "in", ops: &[Fixed(0, W::Wd), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xE5], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 1 },  // in ax imm8
    Form { mnem: In, mnemonic: "in", ops: &[Fixed(0, W::L), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xE5], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 1 },  // in eax imm8
    Form { mnem: In, mnemonic: "in", ops: &[Fixed(0, W::B), Fixed(2, W::Wd)], pp: &[], map: Map::Legacy, opcode: &[0xEC], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // in al dx
    Form { mnem: In, mnemonic: "in", ops: &[Fixed(0, W::Wd), Fixed(2, W::Wd)], pp: &[], map: Map::Legacy, opcode: &[0xED], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // in ax dx
    Form { mnem: In, mnemonic: "in", ops: &[Fixed(0, W::L), Fixed(2, W::Wd)], pp: &[], map: Map::Legacy, opcode: &[0xED], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // in eax dx
    Form { mnem: Inc, mnemonic: "inc", ops: &[Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0xFE], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // inc r8/m8
    Form { mnem: Inc, mnemonic: "inc", ops: &[Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0xFF], plus_r: false, rexw: ByWidth, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // inc rv/mv
    Form { mnem: Int, mnemonic: "int", ops: &[Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xCD], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 0 },  // int imm8
    Form { mnem: Int3, mnemonic: "int3", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0xCC], plus_r: false, rexw: Default64, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // int3
    Form { mnem: Invd, mnemonic: "invd", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x08], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // invd
    Form { mnem: Iretq, mnemonic: "iretq", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0xCF], plus_r: false, rexw: W1, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // iretq
    Form { mnem: Lahf, mnemonic: "lahf", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0x9F], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // lahf ah
    Form { mnem: Lea, mnemonic: "lea", ops: &[Reg(W::Wd), MemAny], pp: &[], map: Map::Legacy, opcode: &[0x67, 0x8D], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // lea r16 mem
    Form { mnem: Lea, mnemonic: "lea", ops: &[Reg(W::L), MemAny], pp: &[], map: Map::Legacy, opcode: &[0x8D], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // lea r32 mem
    Form { mnem: Lea, mnemonic: "lea", ops: &[Reg(W::Q), MemAny], pp: &[], map: Map::Legacy, opcode: &[0x8D], plus_r: false, rexw: W1, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // lea r64 mem
    Form { mnem: Leave, mnemonic: "leave", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0xC9], plus_r: false, rexw: Default64, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // leave
    Form { mnem: Lfence, mnemonic: "lfence", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0xAE, 0xE8], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // lfence
    Form { mnem: Lgdt, mnemonic: "lgdt", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0x01], plus_r: false, rexw: W0, reg: Ext(2), rm: 0, imm: None, imm_op: 255 },  // lgdt mem
    Form { mnem: Lidt, mnemonic: "lidt", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0x01], plus_r: false, rexw: W0, reg: Ext(3), rm: 0, imm: None, imm_op: 255 },  // lidt mem
    Form { mnem: Mfence, mnemonic: "mfence", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0xAE, 0xF0], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // mfence
    Form { mnem: Monitor, mnemonic: "monitor", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x01, 0xC8], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // monitor mem(ds:zax) ecx edx
    Form { mnem: Mov, mnemonic: "mov", ops: &[Rm(W::B), Reg(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x88], plus_r: false, rexw: W0, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // mov r8/m8 r8
    Form { mnem: Mov, mnemonic: "mov", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x89], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // mov rv/mv rv
    Form { mnem: Mov, mnemonic: "mov", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC6], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // mov r8/m8 imm8
    Form { mnem: Mov, mnemonic: "mov", ops: &[Rm(W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0xC7], plus_r: false, rexw: ByWidth, reg: Ext(0), rm: 0, imm: Some(ImmC::Iv), imm_op: 1 },  // mov rv/mv immv
    Form { mnem: Mov, mnemonic: "mov", ops: &[Reg(W::B), Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x8A], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // mov r8 r8/m8
    Form { mnem: Mov, mnemonic: "mov", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x8B], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // mov rv rv/mv
    Form { mnem: Mov, mnemonic: "mov", ops: &[Reg(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xB0], plus_r: true, rexw: W0, reg: NoReg, rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // mov r8 imm8
    Form { mnem: Mov, mnemonic: "mov", ops: &[Reg(W::Wd), Imm(ImmC::Iw)], pp: &[], map: Map::Legacy, opcode: &[0xB8], plus_r: true, rexw: W0, reg: NoReg, rm: 0, imm: Some(ImmC::Iw), imm_op: 1 },  // mov r16 imm16
    Form { mnem: Mov, mnemonic: "mov", ops: &[Reg(W::L), Imm(ImmC::Id)], pp: &[], map: Map::Legacy, opcode: &[0xB8], plus_r: true, rexw: W0, reg: NoReg, rm: 0, imm: Some(ImmC::Id), imm_op: 1 },  // mov r32 imm32
    Form { mnem: Mov, mnemonic: "mov", ops: &[Reg(W::Q), Imm(ImmC::Iq)], pp: &[], map: Map::Legacy, opcode: &[0xB8], plus_r: true, rexw: W1, reg: NoReg, rm: 0, imm: Some(ImmC::Iq), imm_op: 1 },  // mov r64 imm64
    Form { mnem: Movnti, mnemonic: "movnti", ops: &[Mem(W::Y), Reg(W::Y)], pp: &[], map: Map::Op0F, opcode: &[0xC3], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // movnti my ry
    Form { mnem: Movsx, mnemonic: "movsx", ops: &[Reg(W::V), Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0xBE], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // movsx rv r8/m8
    Form { mnem: Movsx, mnemonic: "movsx", ops: &[Reg(W::Y), Rm(W::Wd)], pp: &[], map: Map::Op0F, opcode: &[0xBF], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // movsx ry r16/m16
    Form { mnem: Movsxd, mnemonic: "movsxd", ops: &[Reg(W::Wd), Rm(W::Wd)], pp: &[], map: Map::Legacy, opcode: &[0x63], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // movsxd r16 r16/m16
    Form { mnem: Movsxd, mnemonic: "movsxd", ops: &[Reg(W::L), Rm(W::L)], pp: &[], map: Map::Legacy, opcode: &[0x63], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // movsxd r32 r32/m32
    Form { mnem: Movsxd, mnemonic: "movsxd", ops: &[Reg(W::Q), Rm(W::L)], pp: &[], map: Map::Legacy, opcode: &[0x63], plus_r: false, rexw: W1, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // movsxd r64 r32/m32
    Form { mnem: Movzx, mnemonic: "movzx", ops: &[Reg(W::V), Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0xB6], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // movzx rv r8/m8
    Form { mnem: Movzx, mnemonic: "movzx", ops: &[Reg(W::L), Rm(W::Wd)], pp: &[], map: Map::Op0F, opcode: &[0xB7], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // movzx r32 r16/m16
    Form { mnem: Movzx, mnemonic: "movzx", ops: &[Reg(W::Q), Rm(W::Wd)], pp: &[], map: Map::Op0F, opcode: &[0xB7], plus_r: false, rexw: W1, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // movzx r64 r16/m16
    Form { mnem: Mul, mnemonic: "mul", ops: &[Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0xF6], plus_r: false, rexw: W0, reg: Ext(4), rm: 0, imm: None, imm_op: 255 },  // mul ax r8/m8
    Form { mnem: Mul, mnemonic: "mul", ops: &[Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0xF7], plus_r: false, rexw: ByWidth, reg: Ext(4), rm: 0, imm: None, imm_op: 255 },  // mul dxv axv rv/mv
    Form { mnem: Mwait, mnemonic: "mwait", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x01, 0xC9], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // mwait eax ecx
    Form { mnem: Neg, mnemonic: "neg", ops: &[Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0xF6], plus_r: false, rexw: W0, reg: Ext(3), rm: 0, imm: None, imm_op: 255 },  // neg r8/m8
    Form { mnem: Neg, mnemonic: "neg", ops: &[Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0xF7], plus_r: false, rexw: ByWidth, reg: Ext(3), rm: 0, imm: None, imm_op: 255 },  // neg rv/mv
    Form { mnem: Nop, mnemonic: "nop", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0x90], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // nop
    Form { mnem: Nop, mnemonic: "nop", ops: &[Rm(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x1F], plus_r: false, rexw: ByWidth, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // nop rv/mv
    Form { mnem: Nop, mnemonic: "nop", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Op0F, opcode: &[0x1F], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // nop rv/mv rv
    Form { mnem: Not, mnemonic: "not", ops: &[Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0xF6], plus_r: false, rexw: W0, reg: Ext(2), rm: 0, imm: None, imm_op: 255 },  // not r8/m8
    Form { mnem: Not, mnemonic: "not", ops: &[Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0xF7], plus_r: false, rexw: ByWidth, reg: Ext(2), rm: 0, imm: None, imm_op: 255 },  // not rv/mv
    Form { mnem: Or, mnemonic: "or", ops: &[Fixed(0, W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x0C], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 1 },  // or al imm8
    Form { mnem: Or, mnemonic: "or", ops: &[Fixed(0, W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x0D], plus_r: false, rexw: ByWidth, reg: NoReg, rm: 255, imm: Some(ImmC::Iv), imm_op: 1 },  // or axv immv
    Form { mnem: Or, mnemonic: "or", ops: &[Rm(W::B), Reg(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x08], plus_r: false, rexw: W0, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // or r8/m8 r8
    Form { mnem: Or, mnemonic: "or", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x09], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // or rv/mv rv
    Form { mnem: Or, mnemonic: "or", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x80], plus_r: false, rexw: W0, reg: Ext(1), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // or r8/m8 imm8
    Form { mnem: Or, mnemonic: "or", ops: &[Rm(W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x81], plus_r: false, rexw: ByWidth, reg: Ext(1), rm: 0, imm: Some(ImmC::Iv), imm_op: 1 },  // or rv/mv immv
    Form { mnem: Or, mnemonic: "or", ops: &[Rm(W::V), Imm(ImmC::Imms8)], pp: &[], map: Map::Legacy, opcode: &[0x83], plus_r: false, rexw: ByWidth, reg: Ext(1), rm: 0, imm: Some(ImmC::Imms8), imm_op: 1 },  // or rv/mv imms8
    Form { mnem: Or, mnemonic: "or", ops: &[Reg(W::B), Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x0A], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // or r8 r8/m8
    Form { mnem: Or, mnemonic: "or", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x0B], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // or rv rv/mv
    Form { mnem: Out, mnemonic: "out", ops: &[Imm(ImmC::Ib), Fixed(0, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xE6], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 0 },  // out imm8 al
    Form { mnem: Out, mnemonic: "out", ops: &[Imm(ImmC::Ib), Fixed(0, W::Wd)], pp: &[], map: Map::Legacy, opcode: &[0xE7], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 0 },  // out imm8 ax
    Form { mnem: Out, mnemonic: "out", ops: &[Imm(ImmC::Ib), Fixed(0, W::L)], pp: &[], map: Map::Legacy, opcode: &[0xE7], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 0 },  // out imm8 eax
    Form { mnem: Out, mnemonic: "out", ops: &[Fixed(2, W::Wd), Fixed(0, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xEE], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // out dx al
    Form { mnem: Out, mnemonic: "out", ops: &[Fixed(2, W::Wd), Fixed(0, W::Wd)], pp: &[], map: Map::Legacy, opcode: &[0xEF], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // out dx ax
    Form { mnem: Out, mnemonic: "out", ops: &[Fixed(2, W::Wd), Fixed(0, W::L)], pp: &[], map: Map::Legacy, opcode: &[0xEF], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // out dx eax
    Form { mnem: Pop, mnemonic: "pop", ops: &[Rm(W::Wd)], pp: &[], map: Map::Legacy, opcode: &[0x8F], plus_r: false, rexw: Default64, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // pop r16/m16
    Form { mnem: Pop, mnemonic: "pop", ops: &[Rm(W::Q)], pp: &[], map: Map::Legacy, opcode: &[0x8F], plus_r: false, rexw: Default64, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // pop r64/m64
    Form { mnem: Pop, mnemonic: "pop", ops: &[Reg(W::Wd)], pp: &[], map: Map::Legacy, opcode: &[0x58], plus_r: true, rexw: Default64, reg: NoReg, rm: 0, imm: None, imm_op: 255 },  // pop r16
    Form { mnem: Pop, mnemonic: "pop", ops: &[Reg(W::Q)], pp: &[], map: Map::Legacy, opcode: &[0x58], plus_r: true, rexw: Default64, reg: NoReg, rm: 0, imm: None, imm_op: 255 },  // pop r64
    Form { mnem: Prefetchnta, mnemonic: "prefetchnta", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0x18], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // prefetchnta mem
    Form { mnem: Prefetcht0, mnemonic: "prefetcht0", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0x18], plus_r: false, rexw: W0, reg: Ext(1), rm: 0, imm: None, imm_op: 255 },  // prefetcht0 mem
    Form { mnem: Prefetcht1, mnemonic: "prefetcht1", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0x18], plus_r: false, rexw: W0, reg: Ext(2), rm: 0, imm: None, imm_op: 255 },  // prefetcht1 mem
    Form { mnem: Prefetcht2, mnemonic: "prefetcht2", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0x18], plus_r: false, rexw: W0, reg: Ext(3), rm: 0, imm: None, imm_op: 255 },  // prefetcht2 mem
    Form { mnem: Prefetchw, mnemonic: "prefetchw", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0x0D], plus_r: false, rexw: W0, reg: Ext(1), rm: 0, imm: None, imm_op: 255 },  // prefetchw mem
    Form { mnem: Push, mnemonic: "push", ops: &[Rm(W::Wd)], pp: &[], map: Map::Legacy, opcode: &[0xFF], plus_r: false, rexw: Default64, reg: Ext(6), rm: 0, imm: None, imm_op: 255 },  // push r16/m16
    Form { mnem: Push, mnemonic: "push", ops: &[Rm(W::Q)], pp: &[], map: Map::Legacy, opcode: &[0xFF], plus_r: false, rexw: Default64, reg: Ext(6), rm: 0, imm: None, imm_op: 255 },  // push r64/m64
    Form { mnem: Push, mnemonic: "push", ops: &[Reg(W::Wd)], pp: &[], map: Map::Legacy, opcode: &[0x50], plus_r: true, rexw: Default64, reg: NoReg, rm: 0, imm: None, imm_op: 255 },  // push r16
    Form { mnem: Push, mnemonic: "push", ops: &[Reg(W::Q)], pp: &[], map: Map::Legacy, opcode: &[0x50], plus_r: true, rexw: Default64, reg: NoReg, rm: 0, imm: None, imm_op: 255 },  // push r64
    Form { mnem: Push, mnemonic: "push", ops: &[Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x6A], plus_r: false, rexw: Default64, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 0 },  // push imm8
    Form { mnem: Push, mnemonic: "push", ops: &[Imm(ImmC::Iw)], pp: &[], map: Map::Legacy, opcode: &[0x68], plus_r: false, rexw: Default64, reg: NoReg, rm: 255, imm: Some(ImmC::Iw), imm_op: 0 },  // push imm16
    Form { mnem: Push, mnemonic: "push", ops: &[Imm(ImmC::Id)], pp: &[], map: Map::Legacy, opcode: &[0x68], plus_r: false, rexw: Default64, reg: NoReg, rm: 255, imm: Some(ImmC::Id), imm_op: 0 },  // push imms32
    Form { mnem: Rcl, mnemonic: "rcl", ops: &[Rm(W::B), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD2], plus_r: false, rexw: W0, reg: Ext(2), rm: 0, imm: None, imm_op: 255 },  // rcl r8/m8 cl
    Form { mnem: Rcl, mnemonic: "rcl", ops: &[Rm(W::V), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD3], plus_r: false, rexw: ByWidth, reg: Ext(2), rm: 0, imm: None, imm_op: 255 },  // rcl rv/mv cl
    Form { mnem: Rcl, mnemonic: "rcl", ops: &[Rm(W::B), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD0], plus_r: false, rexw: W0, reg: Ext(2), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // rcl r8/m8 1
    Form { mnem: Rcl, mnemonic: "rcl", ops: &[Rm(W::V), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD1], plus_r: false, rexw: ByWidth, reg: Ext(2), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // rcl rv/mv 1
    Form { mnem: Rcl, mnemonic: "rcl", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC0], plus_r: false, rexw: W0, reg: Ext(2), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // rcl r8/m8 imm8
    Form { mnem: Rcl, mnemonic: "rcl", ops: &[Rm(W::V), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC1], plus_r: false, rexw: ByWidth, reg: Ext(2), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // rcl rv/mv imm8
    Form { mnem: Rcr, mnemonic: "rcr", ops: &[Rm(W::B), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD2], plus_r: false, rexw: W0, reg: Ext(3), rm: 0, imm: None, imm_op: 255 },  // rcr r8/m8 cl
    Form { mnem: Rcr, mnemonic: "rcr", ops: &[Rm(W::V), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD3], plus_r: false, rexw: ByWidth, reg: Ext(3), rm: 0, imm: None, imm_op: 255 },  // rcr rv/mv cl
    Form { mnem: Rcr, mnemonic: "rcr", ops: &[Rm(W::B), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD0], plus_r: false, rexw: W0, reg: Ext(3), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // rcr r8/m8 1
    Form { mnem: Rcr, mnemonic: "rcr", ops: &[Rm(W::V), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD1], plus_r: false, rexw: ByWidth, reg: Ext(3), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // rcr rv/mv 1
    Form { mnem: Rcr, mnemonic: "rcr", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC0], plus_r: false, rexw: W0, reg: Ext(3), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // rcr r8/m8 imm8
    Form { mnem: Rcr, mnemonic: "rcr", ops: &[Rm(W::V), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC1], plus_r: false, rexw: ByWidth, reg: Ext(3), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // rcr rv/mv imm8
    Form { mnem: Rdmsr, mnemonic: "rdmsr", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x32], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // rdmsr edx eax ecx
    Form { mnem: Rdpkru, mnemonic: "rdpkru", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x01, 0xEE], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // rdpkru edx eax ecx
    Form { mnem: Rdpmc, mnemonic: "rdpmc", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x33], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // rdpmc edx eax ecx
    Form { mnem: Rdrand, mnemonic: "rdrand", ops: &[Reg(W::V)], pp: &[], map: Map::Op0F, opcode: &[0xC7], plus_r: false, rexw: ByWidth, reg: Ext(6), rm: 0, imm: None, imm_op: 255 },  // rdrand rv
    Form { mnem: Rdseed, mnemonic: "rdseed", ops: &[Reg(W::V)], pp: &[], map: Map::Op0F, opcode: &[0xC7], plus_r: false, rexw: ByWidth, reg: Ext(7), rm: 0, imm: None, imm_op: 255 },  // rdseed rv
    Form { mnem: Rdtsc, mnemonic: "rdtsc", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x31], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // rdtsc edx eax
    Form { mnem: Rdtscp, mnemonic: "rdtscp", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x01, 0xF9], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // rdtscp edx eax ecx
    Form { mnem: Ret, mnemonic: "ret", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0xC3], plus_r: false, rexw: Default64, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // ret
    Form { mnem: Rol, mnemonic: "rol", ops: &[Rm(W::B), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD2], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // rol r8/m8 cl
    Form { mnem: Rol, mnemonic: "rol", ops: &[Rm(W::V), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD3], plus_r: false, rexw: ByWidth, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // rol rv/mv cl
    Form { mnem: Rol, mnemonic: "rol", ops: &[Rm(W::B), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD0], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // rol r8/m8 1
    Form { mnem: Rol, mnemonic: "rol", ops: &[Rm(W::V), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD1], plus_r: false, rexw: ByWidth, reg: Ext(0), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // rol rv/mv 1
    Form { mnem: Rol, mnemonic: "rol", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC0], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // rol r8/m8 imm8
    Form { mnem: Rol, mnemonic: "rol", ops: &[Rm(W::V), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC1], plus_r: false, rexw: ByWidth, reg: Ext(0), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // rol rv/mv imm8
    Form { mnem: Ror, mnemonic: "ror", ops: &[Rm(W::B), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD2], plus_r: false, rexw: W0, reg: Ext(1), rm: 0, imm: None, imm_op: 255 },  // ror r8/m8 cl
    Form { mnem: Ror, mnemonic: "ror", ops: &[Rm(W::V), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD3], plus_r: false, rexw: ByWidth, reg: Ext(1), rm: 0, imm: None, imm_op: 255 },  // ror rv/mv cl
    Form { mnem: Ror, mnemonic: "ror", ops: &[Rm(W::B), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD0], plus_r: false, rexw: W0, reg: Ext(1), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // ror r8/m8 1
    Form { mnem: Ror, mnemonic: "ror", ops: &[Rm(W::V), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD1], plus_r: false, rexw: ByWidth, reg: Ext(1), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // ror rv/mv 1
    Form { mnem: Ror, mnemonic: "ror", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC0], plus_r: false, rexw: W0, reg: Ext(1), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // ror r8/m8 imm8
    Form { mnem: Ror, mnemonic: "ror", ops: &[Rm(W::V), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC1], plus_r: false, rexw: ByWidth, reg: Ext(1), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // ror rv/mv imm8
    Form { mnem: Sahf, mnemonic: "sahf", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0x9E], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // sahf ah
    Form { mnem: Sal, mnemonic: "sal", ops: &[Rm(W::B), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD2], plus_r: false, rexw: W0, reg: Ext(4), rm: 0, imm: None, imm_op: 255 },  // sal r8/m8 cl
    Form { mnem: Sal, mnemonic: "sal", ops: &[Rm(W::V), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD3], plus_r: false, rexw: ByWidth, reg: Ext(4), rm: 0, imm: None, imm_op: 255 },  // sal rv/mv cl
    Form { mnem: Sal, mnemonic: "sal", ops: &[Rm(W::B), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD0], plus_r: false, rexw: W0, reg: Ext(4), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // sal r8/m8 1
    Form { mnem: Sal, mnemonic: "sal", ops: &[Rm(W::V), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD1], plus_r: false, rexw: ByWidth, reg: Ext(4), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // sal rv/mv 1
    Form { mnem: Sal, mnemonic: "sal", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC0], plus_r: false, rexw: W0, reg: Ext(4), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // sal r8/m8 imm8
    Form { mnem: Sal, mnemonic: "sal", ops: &[Rm(W::V), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC1], plus_r: false, rexw: ByWidth, reg: Ext(4), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // sal rv/mv imm8
    Form { mnem: Sar, mnemonic: "sar", ops: &[Rm(W::B), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD2], plus_r: false, rexw: W0, reg: Ext(7), rm: 0, imm: None, imm_op: 255 },  // sar r8/m8 cl
    Form { mnem: Sar, mnemonic: "sar", ops: &[Rm(W::V), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD3], plus_r: false, rexw: ByWidth, reg: Ext(7), rm: 0, imm: None, imm_op: 255 },  // sar rv/mv cl
    Form { mnem: Sar, mnemonic: "sar", ops: &[Rm(W::B), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD0], plus_r: false, rexw: W0, reg: Ext(7), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // sar r8/m8 1
    Form { mnem: Sar, mnemonic: "sar", ops: &[Rm(W::V), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD1], plus_r: false, rexw: ByWidth, reg: Ext(7), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // sar rv/mv 1
    Form { mnem: Sar, mnemonic: "sar", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC0], plus_r: false, rexw: W0, reg: Ext(7), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // sar r8/m8 imm8
    Form { mnem: Sar, mnemonic: "sar", ops: &[Rm(W::V), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC1], plus_r: false, rexw: ByWidth, reg: Ext(7), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // sar rv/mv imm8
    Form { mnem: Sbb, mnemonic: "sbb", ops: &[Fixed(0, W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x1C], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 1 },  // sbb al imm8
    Form { mnem: Sbb, mnemonic: "sbb", ops: &[Fixed(0, W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x1D], plus_r: false, rexw: ByWidth, reg: NoReg, rm: 255, imm: Some(ImmC::Iv), imm_op: 1 },  // sbb axv immv
    Form { mnem: Sbb, mnemonic: "sbb", ops: &[Rm(W::B), Reg(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x18], plus_r: false, rexw: W0, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // sbb r8/m8 r8
    Form { mnem: Sbb, mnemonic: "sbb", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x19], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // sbb rv/mv rv
    Form { mnem: Sbb, mnemonic: "sbb", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x80], plus_r: false, rexw: W0, reg: Ext(3), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // sbb r8/m8 imm8
    Form { mnem: Sbb, mnemonic: "sbb", ops: &[Rm(W::V), Imm(ImmC::Imms8)], pp: &[], map: Map::Legacy, opcode: &[0x83], plus_r: false, rexw: ByWidth, reg: Ext(3), rm: 0, imm: Some(ImmC::Imms8), imm_op: 1 },  // sbb rv/mv imms8
    Form { mnem: Sbb, mnemonic: "sbb", ops: &[Rm(W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x81], plus_r: false, rexw: ByWidth, reg: Ext(3), rm: 0, imm: Some(ImmC::Iv), imm_op: 1 },  // sbb rv/mv immv
    Form { mnem: Sbb, mnemonic: "sbb", ops: &[Reg(W::B), Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x1A], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // sbb r8 r8/m8
    Form { mnem: Sbb, mnemonic: "sbb", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x1B], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // sbb rv rv/mv
    Form { mnem: Serialize, mnemonic: "serialize", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x01, 0xE8], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // serialize
    Form { mnem: Seta, mnemonic: "seta", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x97], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // seta r8/m8
    Form { mnem: Setae, mnemonic: "setae", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x93], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setae r8/m8
    Form { mnem: Setb, mnemonic: "setb", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x92], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setb r8/m8
    Form { mnem: Setbe, mnemonic: "setbe", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x96], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setbe r8/m8
    Form { mnem: Setc, mnemonic: "setc", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x92], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setc r8/m8
    Form { mnem: Sete, mnemonic: "sete", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x94], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // sete r8/m8
    Form { mnem: Setg, mnemonic: "setg", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x9F], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setg r8/m8
    Form { mnem: Setge, mnemonic: "setge", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x9D], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setge r8/m8
    Form { mnem: Setl, mnemonic: "setl", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x9C], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setl r8/m8
    Form { mnem: Setle, mnemonic: "setle", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x9E], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setle r8/m8
    Form { mnem: Setna, mnemonic: "setna", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x96], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setna r8/m8
    Form { mnem: Setnae, mnemonic: "setnae", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x92], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setnae r8/m8
    Form { mnem: Setnb, mnemonic: "setnb", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x93], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setnb r8/m8
    Form { mnem: Setnbe, mnemonic: "setnbe", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x97], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setnbe r8/m8
    Form { mnem: Setnc, mnemonic: "setnc", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x93], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setnc r8/m8
    Form { mnem: Setne, mnemonic: "setne", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x95], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setne r8/m8
    Form { mnem: Setng, mnemonic: "setng", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x9E], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setng r8/m8
    Form { mnem: Setnge, mnemonic: "setnge", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x9C], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setnge r8/m8
    Form { mnem: Setnl, mnemonic: "setnl", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x9D], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setnl r8/m8
    Form { mnem: Setnle, mnemonic: "setnle", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x9F], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setnle r8/m8
    Form { mnem: Setno, mnemonic: "setno", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x91], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setno r8/m8
    Form { mnem: Setnp, mnemonic: "setnp", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x9B], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setnp r8/m8
    Form { mnem: Setns, mnemonic: "setns", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x99], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setns r8/m8
    Form { mnem: Setnz, mnemonic: "setnz", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x95], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setnz r8/m8
    Form { mnem: Seto, mnemonic: "seto", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x90], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // seto r8/m8
    Form { mnem: Setp, mnemonic: "setp", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x9A], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setp r8/m8
    Form { mnem: Setpe, mnemonic: "setpe", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x9A], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setpe r8/m8
    Form { mnem: Setpo, mnemonic: "setpo", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x9B], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setpo r8/m8
    Form { mnem: Sets, mnemonic: "sets", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x98], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // sets r8/m8
    Form { mnem: Setz, mnemonic: "setz", ops: &[Rm(W::B)], pp: &[], map: Map::Op0F, opcode: &[0x94], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // setz r8/m8
    Form { mnem: Sfence, mnemonic: "sfence", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0xAE, 0xF8], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // sfence
    Form { mnem: Sgdt, mnemonic: "sgdt", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0x01], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: None, imm_op: 255 },  // sgdt mem
    Form { mnem: Shl, mnemonic: "shl", ops: &[Rm(W::B), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD2], plus_r: false, rexw: W0, reg: Ext(4), rm: 0, imm: None, imm_op: 255 },  // shl r8/m8 cl
    Form { mnem: Shl, mnemonic: "shl", ops: &[Rm(W::V), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD3], plus_r: false, rexw: ByWidth, reg: Ext(4), rm: 0, imm: None, imm_op: 255 },  // shl rv/mv cl
    Form { mnem: Shl, mnemonic: "shl", ops: &[Rm(W::B), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD0], plus_r: false, rexw: W0, reg: Ext(4), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // shl r8/m8 1
    Form { mnem: Shl, mnemonic: "shl", ops: &[Rm(W::V), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD1], plus_r: false, rexw: ByWidth, reg: Ext(4), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // shl rv/mv 1
    Form { mnem: Shl, mnemonic: "shl", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC0], plus_r: false, rexw: W0, reg: Ext(4), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // shl r8/m8 imm8
    Form { mnem: Shl, mnemonic: "shl", ops: &[Rm(W::V), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC1], plus_r: false, rexw: ByWidth, reg: Ext(4), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // shl rv/mv imm8
    Form { mnem: Shr, mnemonic: "shr", ops: &[Rm(W::B), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD2], plus_r: false, rexw: W0, reg: Ext(5), rm: 0, imm: None, imm_op: 255 },  // shr r8/m8 cl
    Form { mnem: Shr, mnemonic: "shr", ops: &[Rm(W::V), Fixed(1, W::B)], pp: &[], map: Map::Legacy, opcode: &[0xD3], plus_r: false, rexw: ByWidth, reg: Ext(5), rm: 0, imm: None, imm_op: 255 },  // shr rv/mv cl
    Form { mnem: Shr, mnemonic: "shr", ops: &[Rm(W::B), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD0], plus_r: false, rexw: W0, reg: Ext(5), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // shr r8/m8 1
    Form { mnem: Shr, mnemonic: "shr", ops: &[Rm(W::V), Imm(ImmC::One)], pp: &[], map: Map::Legacy, opcode: &[0xD1], plus_r: false, rexw: ByWidth, reg: Ext(5), rm: 0, imm: Some(ImmC::One), imm_op: 1 },  // shr rv/mv 1
    Form { mnem: Shr, mnemonic: "shr", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC0], plus_r: false, rexw: W0, reg: Ext(5), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // shr r8/m8 imm8
    Form { mnem: Shr, mnemonic: "shr", ops: &[Rm(W::V), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xC1], plus_r: false, rexw: ByWidth, reg: Ext(5), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // shr rv/mv imm8
    Form { mnem: Sidt, mnemonic: "sidt", ops: &[MemAny], pp: &[], map: Map::Op0F, opcode: &[0x01], plus_r: false, rexw: W0, reg: Ext(1), rm: 0, imm: None, imm_op: 255 },  // sidt mem
    Form { mnem: Stc, mnemonic: "stc", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0xF9], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // stc
    Form { mnem: Std, mnemonic: "std", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0xFD], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // std
    Form { mnem: Sti, mnemonic: "sti", ops: &[], pp: &[], map: Map::Legacy, opcode: &[0xFB], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // sti
    Form { mnem: Sub, mnemonic: "sub", ops: &[Fixed(0, W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x2C], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 1 },  // sub al imm8
    Form { mnem: Sub, mnemonic: "sub", ops: &[Fixed(0, W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x2D], plus_r: false, rexw: ByWidth, reg: NoReg, rm: 255, imm: Some(ImmC::Iv), imm_op: 1 },  // sub axv immv
    Form { mnem: Sub, mnemonic: "sub", ops: &[Rm(W::B), Reg(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x28], plus_r: false, rexw: W0, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // sub r8/m8 r8
    Form { mnem: Sub, mnemonic: "sub", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x29], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // sub rv/mv rv
    Form { mnem: Sub, mnemonic: "sub", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x80], plus_r: false, rexw: W0, reg: Ext(5), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // sub r8/m8 imm8
    Form { mnem: Sub, mnemonic: "sub", ops: &[Rm(W::V), Imm(ImmC::Imms8)], pp: &[], map: Map::Legacy, opcode: &[0x83], plus_r: false, rexw: ByWidth, reg: Ext(5), rm: 0, imm: Some(ImmC::Imms8), imm_op: 1 },  // sub rv/mv imms8
    Form { mnem: Sub, mnemonic: "sub", ops: &[Rm(W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x81], plus_r: false, rexw: ByWidth, reg: Ext(5), rm: 0, imm: Some(ImmC::Iv), imm_op: 1 },  // sub rv/mv immv
    Form { mnem: Sub, mnemonic: "sub", ops: &[Reg(W::B), Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x2A], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // sub r8 r8/m8
    Form { mnem: Sub, mnemonic: "sub", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x2B], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // sub rv rv/mv
    Form { mnem: Swapgs, mnemonic: "swapgs", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x01, 0xF8], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // swapgs
    Form { mnem: Syscall, mnemonic: "syscall", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x05], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // syscall
    Form { mnem: Sysenter, mnemonic: "sysenter", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x34], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // sysenter
    Form { mnem: Sysexit, mnemonic: "sysexit", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x35], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // sysexit
    Form { mnem: Sysret, mnemonic: "sysret", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x07], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // sysret
    Form { mnem: Test, mnemonic: "test", ops: &[Rm(W::B), Reg(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x84], plus_r: false, rexw: W0, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // test r8/m8 r8
    Form { mnem: Test, mnemonic: "test", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x85], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // test rv/mv rv
    Form { mnem: Test, mnemonic: "test", ops: &[Fixed(0, W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xA8], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 1 },  // test al imm8
    Form { mnem: Test, mnemonic: "test", ops: &[Fixed(0, W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0xA9], plus_r: false, rexw: ByWidth, reg: NoReg, rm: 255, imm: Some(ImmC::Iv), imm_op: 1 },  // test axv immv
    Form { mnem: Test, mnemonic: "test", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0xF6], plus_r: false, rexw: W0, reg: Ext(0), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // test r8/m8 imm8
    Form { mnem: Test, mnemonic: "test", ops: &[Rm(W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0xF7], plus_r: false, rexw: ByWidth, reg: Ext(0), rm: 0, imm: Some(ImmC::Iv), imm_op: 1 },  // test rv/mv immv
    Form { mnem: Ud2, mnemonic: "ud2", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x0B], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // ud2
    Form { mnem: Wbinvd, mnemonic: "wbinvd", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x09], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // wbinvd
    Form { mnem: Wrmsr, mnemonic: "wrmsr", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x30], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // wrmsr edx eax ecx
    Form { mnem: Xadd, mnemonic: "xadd", ops: &[Rm(W::B), Reg(W::B)], pp: &[], map: Map::Op0F, opcode: &[0xC0], plus_r: false, rexw: W0, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // xadd r8/m8 r8
    Form { mnem: Xadd, mnemonic: "xadd", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Op0F, opcode: &[0xC1], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // xadd rv/mv rv
    Form { mnem: Xchg, mnemonic: "xchg", ops: &[Fixed(0, W::Wd), Reg(W::Wd)], pp: &[], map: Map::Legacy, opcode: &[0x90], plus_r: true, rexw: W0, reg: NoReg, rm: 0, imm: None, imm_op: 255 },  // xchg ax r16
    Form { mnem: Xchg, mnemonic: "xchg", ops: &[Fixed(0, W::L), Reg(W::L)], pp: &[], map: Map::Legacy, opcode: &[0x90], plus_r: true, rexw: W0, reg: NoReg, rm: 0, imm: None, imm_op: 255 },  // xchg eax r32
    Form { mnem: Xchg, mnemonic: "xchg", ops: &[Fixed(0, W::Q), Reg(W::Q)], pp: &[], map: Map::Legacy, opcode: &[0x90], plus_r: true, rexw: W1, reg: NoReg, rm: 0, imm: None, imm_op: 255 },  // xchg rax r64
    Form { mnem: Xchg, mnemonic: "xchg", ops: &[Reg(W::Wd), Fixed(0, W::Wd)], pp: &[], map: Map::Legacy, opcode: &[0x90], plus_r: true, rexw: W0, reg: NoReg, rm: 0, imm: None, imm_op: 255 },  // xchg r16 ax
    Form { mnem: Xchg, mnemonic: "xchg", ops: &[Reg(W::L), Fixed(0, W::L)], pp: &[], map: Map::Legacy, opcode: &[0x90], plus_r: true, rexw: W0, reg: NoReg, rm: 0, imm: None, imm_op: 255 },  // xchg r32 eax
    Form { mnem: Xchg, mnemonic: "xchg", ops: &[Reg(W::Q), Fixed(0, W::Q)], pp: &[], map: Map::Legacy, opcode: &[0x90], plus_r: true, rexw: W1, reg: NoReg, rm: 0, imm: None, imm_op: 255 },  // xchg r64 rax
    Form { mnem: Xchg, mnemonic: "xchg", ops: &[Rm(W::B), Reg(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x86], plus_r: false, rexw: W0, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // xchg r8/m8 r8
    Form { mnem: Xchg, mnemonic: "xchg", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x87], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // xchg rv/mv rv
    Form { mnem: Xchg, mnemonic: "xchg", ops: &[Reg(W::B), Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x86], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // xchg r8 r8/m8
    Form { mnem: Xchg, mnemonic: "xchg", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x87], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // xchg rv rv/mv
    Form { mnem: Xgetbv, mnemonic: "xgetbv", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x01, 0xD0], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // xgetbv edx eax ecx
    Form { mnem: Xor, mnemonic: "xor", ops: &[Fixed(0, W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x34], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: Some(ImmC::Ib), imm_op: 1 },  // xor al imm8
    Form { mnem: Xor, mnemonic: "xor", ops: &[Fixed(0, W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x35], plus_r: false, rexw: ByWidth, reg: NoReg, rm: 255, imm: Some(ImmC::Iv), imm_op: 1 },  // xor axv immv
    Form { mnem: Xor, mnemonic: "xor", ops: &[Rm(W::B), Reg(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x30], plus_r: false, rexw: W0, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // xor r8/m8 r8
    Form { mnem: Xor, mnemonic: "xor", ops: &[Rm(W::V), Reg(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x31], plus_r: false, rexw: ByWidth, reg: FromOp(1), rm: 0, imm: None, imm_op: 255 },  // xor rv/mv rv
    Form { mnem: Xor, mnemonic: "xor", ops: &[Rm(W::B), Imm(ImmC::Ib)], pp: &[], map: Map::Legacy, opcode: &[0x80], plus_r: false, rexw: W0, reg: Ext(6), rm: 0, imm: Some(ImmC::Ib), imm_op: 1 },  // xor r8/m8 imm8
    Form { mnem: Xor, mnemonic: "xor", ops: &[Rm(W::V), Imm(ImmC::Imms8)], pp: &[], map: Map::Legacy, opcode: &[0x83], plus_r: false, rexw: ByWidth, reg: Ext(6), rm: 0, imm: Some(ImmC::Imms8), imm_op: 1 },  // xor rv/mv imms8
    Form { mnem: Xor, mnemonic: "xor", ops: &[Rm(W::V), Imm(ImmC::Iv)], pp: &[], map: Map::Legacy, opcode: &[0x81], plus_r: false, rexw: ByWidth, reg: Ext(6), rm: 0, imm: Some(ImmC::Iv), imm_op: 1 },  // xor rv/mv immv
    Form { mnem: Xor, mnemonic: "xor", ops: &[Reg(W::B), Rm(W::B)], pp: &[], map: Map::Legacy, opcode: &[0x32], plus_r: false, rexw: W0, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // xor r8 r8/m8
    Form { mnem: Xor, mnemonic: "xor", ops: &[Reg(W::V), Rm(W::V)], pp: &[], map: Map::Legacy, opcode: &[0x33], plus_r: false, rexw: ByWidth, reg: FromOp(0), rm: 1, imm: None, imm_op: 255 },  // xor rv rv/mv
    Form { mnem: Xsetbv, mnemonic: "xsetbv", ops: &[], pp: &[], map: Map::Op0F, opcode: &[0x01, 0xD1], plus_r: false, rexw: W0, reg: NoReg, rm: 255, imm: None, imm_op: 255 },  // xsetbv edx eax ecx
];
