#!/usr/bin/env python3
"""Write doc/diagnostics.md from the catalogue golden.

`tests/diagnostics/catalog.txt` is what `badc --list-diagnostics`
prints, pinned by a unit test; this turns the same rows into the
Markdown reference so the two never disagree. `--check` fails when the
document is stale instead of rewriting it.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GOLDEN = ROOT / "tests" / "diagnostics" / "catalog.txt"
DOC = ROOT / "doc" / "diagnostics.md"

HEAD = """# Diagnostics

Every diagnostic badc prints ends with its code and its name:

```console
unit.c:3: warning: unused variable `x` [B2001] [-Wunused-variable]
unit.c:7: error: `)` expected after cast [B2020] [syntax]
```

The code and the name are stable: a code is never reused or renumbered,
a name is never reused for a different diagnostic. Either selects the
row wherever a selector is accepted:

* `-W<name>` / `-Wno-<name>` report or ignore a controllable row,
  `-Werror=<name>` / `-Wno-error=<name>` raise it to an error or put it
  back, `-Werror` raises every warning, `-w` silences every warning.
  `-Wall`, `-Wextra` and `-Wpedantic` turn on the groups of the same
  names, following gcc's split. A code spelled `B2001` is accepted
  wherever a name is.
* `#pragma GCC diagnostic ignored "-W<name>"` (also `warning`, `error`,
  `push`, `pop`), `#pragma clang diagnostic ...` and MSVC's
  `#pragma warning(disable | error | default | once | suppress | push |
  pop : <number>)` apply from the pragma's position; an MSVC number
  names the row it is an alias of.
* `badc --explain <selector>` prints one row with its aliases;
  `badc --list-diagnostics` prints this table.

A hard row is always an error: its site has no way to continue, and no
option changes it. A note is advisory. The default level and the groups
may change between releases; the code and the name do not.

This file is generated by `scripts/diagnostics_doc.py` from
`tests/diagnostics/catalog.txt`, which `badc --list-diagnostics`
regenerates.

| code | name | default | class | groups | description |
|------|------|---------|-------|--------|-------------|
"""


def rows() -> list[list[str]]:
    lines = GOLDEN.read_text().splitlines()
    out = []
    for line in lines[1:]:
        cells = re.split(r"\s{2,}", line.rstrip(), maxsplit=6)
        if len(cells) != 7:
            raise SystemExit(f"{GOLDEN}: unparsed row: {line!r}")
        out.append(cells)
    return out


def render() -> str:
    body = []
    for code, name, default, cls, groups, status, desc in rows():
        if status == "retired":
            name = f"{name} (retired)"
        desc = desc.replace("|", "\\|")
        body.append(f"| {code} | `{name}` | {default} | {cls} | {groups} | {desc} |")
    return HEAD + "\n".join(body) + "\n"


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        if not DOC.exists() or DOC.read_text() != text:
            print(f"{DOC} is stale; run scripts/diagnostics_doc.py", file=sys.stderr)
            return 1
        return 0
    DOC.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
