#!/usr/bin/env python3
"""Write src/c5/diag/foreign_names.rs: the warning options gcc and clang
define, which tell a name badc does not implement from a misspelling.

    gcc -Q --help=warnings < /dev/null > gcc.txt
    scripts/foreign_warnings.py --gcc gcc.txt --gcc-version "16.2.1" \\
        --clang-td llvm-project/clang/include/clang/Basic --clang-version "21.1.0"

gcc contributes the options its list shows as valid for C, a name taking
a value as the name and its `=` (`format=`); a name with a fixed value
(`suggest-attribute=format`) stays whole. clang contributes every
`DiagGroup<"...">` its Diagnostic*.td files name.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "c5" / "diag" / "foreign_names.rs"


def gcc_names(text: str) -> set[str]:
    """gcc's C warning options, each as gcc's pragma matches it."""
    names: set[str] = set()
    for line in text.splitlines():
        m = re.match(r"^  (-W\S+)\s*(.*)$", line)
        if not m:
            continue
        spelling, rest = m.group(1)[2:], m.group(2)
        langs = re.search(r"\[available in ([^\]]*)\]", rest)
        if langs and "C" not in [s.strip() for s in langs.group(1).split(",")]:
            continue
        if "=" in spelling:
            name, value = spelling.split("=", 1)
            fixed = value and not value.startswith(("<", "["))
            names.add(spelling if fixed else name + "=")
        elif spelling:
            names.add(spelling.split("<", 1)[0])
    return names


def clang_names(td_dir: Path) -> set[str]:
    names: set[str] = set()
    for td in sorted(td_dir.glob("Diagnostic*.td")):
        names.update(re.findall(r'DiagGroup<"([^"]*)"', td.read_text()))
    names.discard("")
    return names


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--gcc", type=Path, required=True)
    ap.add_argument("--gcc-version", required=True)
    ap.add_argument("--clang-td", type=Path, required=True)
    ap.add_argument("--clang-version", required=True)
    args = ap.parse_args()

    gcc = gcc_names(args.gcc.read_text())
    clang = clang_names(args.clang_td)
    rows = []
    for name in sorted(gcc | clang):
        owners = [o for o, s in (("GCC", gcc), ("CLANG", clang)) if name in s]
        rows.append(f'    ("{name}", {" | ".join(owners)}),')
    head = f"""//! The warning options gcc {args.gcc_version} (`-Q --help=warnings`, the
//! options valid for C) and clang {args.clang_version} (Diagnostic*.td)
//! define; a name ending in `=` takes a value. Generated by
//! scripts/foreign_warnings.py; do not edit.

use super::foreign::{{CLANG, GCC}};

#[rustfmt::skip]
pub(super) static NAMES: &[(&str, u8)] = &[
"""
    OUT.write_text(head + "\n".join(rows) + "\n];\n")
    print(f"{len(rows)} names ({len(gcc)} gcc, {len(clang)} clang) -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
